# Generated by Django 4.2.23 on 2025-10-16 07:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("departments", "0011_department_departments_department_tref4ab"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-poçt")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                (
                    "resume",
                    models.FileField(
                        upload_to="resumes/%Y/%m/", verbose_name="CV/Rezume"
                    ),
                ),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="Müraciət Məktubu"),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, verbose_name="Portfolio/LinkedIn URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Alındı"),
                            ("screening", "Sınaq"),
                            ("interview", "Müsahibə"),
                            ("assessment", "Qiymətləndirmə"),
                            ("offer", "Təklif"),
                            ("hired", "İşə Qəbul Edildi"),
                            ("rejected", "Rədd Edildi"),
                            ("withdrawn", "Geri Çəkildi"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Veb Sayt"),
                            ("linkedin", "LinkedIn"),
                            ("job_board", "İş Elanları Saytı"),
                            ("referral", "İstinad"),
                            ("direct", "Birbaşa"),
                            ("agency", "Agentlik"),
                            ("other", "Digər"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="Mənbə",
                    ),
                ),
                (
                    "current_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hazırki Vəzifə"
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Təcrübə İli",
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Gözlənilən Maaş",
                    ),
                ),
                (
                    "notice_period_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Bildiriş Müddəti (Gün)"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reytinq (1-5)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "applied_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Müraciət Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təyin Edilən",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müraciət",
                "verbose_name_plural": "Müraciətlər",
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Vəzifə Adı")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Vakansiya Kodu"
                    ),
                ),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "responsibilities",
                    models.TextField(verbose_name="Vəzifə Öhdəlikləri"),
                ),
                ("requirements", models.TextField(verbose_name="Tələblər")),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, verbose_name="İstisnalı Kvalifikasiyalar"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Tam Ştatlı"),
                            ("part_time", "Qismən Ştatlı"),
                            ("contract", "Müqavilə"),
                            ("temporary", "Müvəqqəti"),
                            ("internship", "Təcrübə"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="İşə Qəbul Növü",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Başlanğıc"),
                            ("junior", "Junior"),
                            ("mid", "Orta"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("manager", "Menecer"),
                        ],
                        default="mid",
                        max_length=20,
                        verbose_name="Təcrübə Səviyyəsi",
                    ),
                ),
                (
                    "number_of_positions",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Vəzifə Sayı",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Minimum Maaş",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Maksimum Maaş",
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "show_salary",
                    models.BooleanField(default=False, verbose_name="Maaşı Göstər"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="İş Yeri")),
                (
                    "remote_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Uzaqdan İş İmkanı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("open", "Açıq"),
                            ("closed", "Bağlı"),
                            ("on_hold", "Gözləmədə"),
                            ("cancelled", "Ləğv Edilmiş"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "posted_date",
                    models.DateField(blank=True, null=True, verbose_name="Elan Tarixi"),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bağlanma Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_job_postings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_postings",
                        to="departments.department",
                        verbose_name="Şöbə",
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_job_postings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşə Qəbul Meneceri",
                    ),
                ),
                (
                    "recruiters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recruited_job_postings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşə Qəbul Komandası",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vakansiya",
                "verbose_name_plural": "Vakansiyalar",
                "ordering": ["-posted_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Telefon"),
                            ("video", "Video"),
                            ("onsite", "Yerində"),
                            ("technical", "Texniki"),
                            ("hr", "HR"),
                            ("final", "Final"),
                        ],
                        max_length=20,
                        verbose_name="Müsahibə Növü",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Planlaşdırılmış Tarix"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="Müddət (Dəqiqə)"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Yer"),
                ),
                (
                    "meeting_link",
                    models.URLField(blank=True, verbose_name="Görüş Linki"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planlaşdırılıb"),
                            ("completed", "Tamamlanıb"),
                            ("cancelled", "Ləğv Edilib"),
                            ("rescheduled", "Yenidən Planlaşdırılıb"),
                            ("no_show", "Gəlmədi"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Rəy")),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reytinq (1-5)",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("strong_yes", "Güclü Bəli"),
                            ("yes", "Bəli"),
                            ("maybe", "Bəlkə"),
                            ("no", "Xeyr"),
                            ("strong_no", "Güclü Xeyr"),
                        ],
                        max_length=20,
                        verbose_name="Tövsiyə",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "interviewers",
                    models.ManyToManyField(
                        related_name="conducted_interviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müsahibə Alanlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Müsahibə",
                "verbose_name_plural": "Müsahibələr",
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalOnboardingTask",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tapşırıq")),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("documentation", "Sənədləşdirmə"),
                            ("equipment", "Avadanlıq"),
                            ("access", "Giriş"),
                            ("training", "Təlim"),
                            ("orientation", "Orientasiya"),
                            ("other", "Digər"),
                        ],
                        default="documentation",
                        max_length=100,
                        verbose_name="Kateqoriya",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("in_progress", "Davam Edir"),
                            ("completed", "Tamamlanıb"),
                            ("skipped", "Ötürülüb"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarix"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarixi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təyin Edilən",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_hire",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yeni İşçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical İşəbaşlama Tapşırığı",
                "verbose_name_plural": "historical İşəbaşlama Tapşırıqları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOffer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "position_title",
                    models.CharField(max_length=200, verbose_name="Vəzifə Adı"),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Maaş"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "bonus_potential",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Bonus Potensialı",
                    ),
                ),
                ("benefits", models.TextField(blank=True, verbose_name="Müavinətlər")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlanğıc Tarixi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("sent", "Göndərildi"),
                            ("accepted", "Qəbul Edildi"),
                            ("rejected", "Rədd Edildi"),
                            ("negotiating", "Müzakirə Edilir"),
                            ("expired", "Müddəti Keçib"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Göndərilmə Tarixi"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Qəbul Tarixi"
                    ),
                ),
                (
                    "response_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Cavab Tarixi"
                    ),
                ),
                (
                    "offer_letter",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Təklif Məktubu",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Təklif",
                "verbose_name_plural": "historical Təkliflər",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalJobPosting",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Vəzifə Adı")),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="Vakansiya Kodu"
                    ),
                ),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "responsibilities",
                    models.TextField(verbose_name="Vəzifə Öhdəlikləri"),
                ),
                ("requirements", models.TextField(verbose_name="Tələblər")),
                (
                    "qualifications",
                    models.TextField(
                        blank=True, verbose_name="İstisnalı Kvalifikasiyalar"
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Tam Ştatlı"),
                            ("part_time", "Qismən Ştatlı"),
                            ("contract", "Müqavilə"),
                            ("temporary", "Müvəqqəti"),
                            ("internship", "Təcrübə"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="İşə Qəbul Növü",
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("entry", "Başlanğıc"),
                            ("junior", "Junior"),
                            ("mid", "Orta"),
                            ("senior", "Senior"),
                            ("lead", "Lead"),
                            ("manager", "Menecer"),
                        ],
                        default="mid",
                        max_length=20,
                        verbose_name="Təcrübə Səviyyəsi",
                    ),
                ),
                (
                    "number_of_positions",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Vəzifə Sayı",
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Minimum Maaş",
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Maksimum Maaş",
                    ),
                ),
                (
                    "salary_currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "show_salary",
                    models.BooleanField(default=False, verbose_name="Maaşı Göstər"),
                ),
                ("location", models.CharField(max_length=200, verbose_name="İş Yeri")),
                (
                    "remote_allowed",
                    models.BooleanField(
                        default=False, verbose_name="Uzaqdan İş İmkanı"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("open", "Açıq"),
                            ("closed", "Bağlı"),
                            ("on_hold", "Gözləmədə"),
                            ("cancelled", "Ləğv Edilmiş"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "posted_date",
                    models.DateField(blank=True, null=True, verbose_name="Elan Tarixi"),
                ),
                (
                    "closing_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bağlanma Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="departments.department",
                        verbose_name="Şöbə",
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşə Qəbul Meneceri",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Vakansiya",
                "verbose_name_plural": "historical Vakansiyalar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalInterview",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Telefon"),
                            ("video", "Video"),
                            ("onsite", "Yerində"),
                            ("technical", "Texniki"),
                            ("hr", "HR"),
                            ("final", "Final"),
                        ],
                        max_length=20,
                        verbose_name="Müsahibə Növü",
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(verbose_name="Planlaşdırılmış Tarix"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(default=60, verbose_name="Müddət (Dəqiqə)"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Yer"),
                ),
                (
                    "meeting_link",
                    models.URLField(blank=True, verbose_name="Görüş Linki"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Planlaşdırılıb"),
                            ("completed", "Tamamlanıb"),
                            ("cancelled", "Ləğv Edilib"),
                            ("rescheduled", "Yenidən Planlaşdırılıb"),
                            ("no_show", "Gəlmədi"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("feedback", models.TextField(blank=True, verbose_name="Rəy")),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reytinq (1-5)",
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("strong_yes", "Güclü Bəli"),
                            ("yes", "Bəli"),
                            ("maybe", "Bəlkə"),
                            ("no", "Xeyr"),
                            ("strong_no", "Güclü Xeyr"),
                        ],
                        max_length=20,
                        verbose_name="Tövsiyə",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Müsahibə",
                "verbose_name_plural": "historical Müsahibələr",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalApplication",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Ad")),
                ("last_name", models.CharField(max_length=100, verbose_name="Soyad")),
                ("email", models.EmailField(max_length=254, verbose_name="E-poçt")),
                ("phone", models.CharField(max_length=20, verbose_name="Telefon")),
                ("resume", models.TextField(max_length=100, verbose_name="CV/Rezume")),
                (
                    "cover_letter",
                    models.TextField(blank=True, verbose_name="Müraciət Məktubu"),
                ),
                (
                    "portfolio_url",
                    models.URLField(blank=True, verbose_name="Portfolio/LinkedIn URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Alındı"),
                            ("screening", "Sınaq"),
                            ("interview", "Müsahibə"),
                            ("assessment", "Qiymətləndirmə"),
                            ("offer", "Təklif"),
                            ("hired", "İşə Qəbul Edildi"),
                            ("rejected", "Rədd Edildi"),
                            ("withdrawn", "Geri Çəkildi"),
                        ],
                        default="received",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Veb Sayt"),
                            ("linkedin", "LinkedIn"),
                            ("job_board", "İş Elanları Saytı"),
                            ("referral", "İstinad"),
                            ("direct", "Birbaşa"),
                            ("agency", "Agentlik"),
                            ("other", "Digər"),
                        ],
                        default="website",
                        max_length=20,
                        verbose_name="Mənbə",
                    ),
                ),
                (
                    "current_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hazırki Vəzifə"
                    ),
                ),
                (
                    "years_of_experience",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="Təcrübə İli",
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Gözlənilən Maaş",
                    ),
                ),
                (
                    "notice_period_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Bildiriş Müddəti (Gün)"
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Reytinq (1-5)",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "applied_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Müraciət Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təyin Edilən",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recruitment.jobposting",
                        verbose_name="Vakansiya",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstinad Edən",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Müraciət",
                "verbose_name_plural": "historical Müraciətlər",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="application",
            name="job_posting",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitment.jobposting",
                verbose_name="Vakansiya",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="referrer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="İstinad Edən",
            ),
        ),
        migrations.CreateModel(
            name="OnboardingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Tapşırıq")),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("documentation", "Sənədləşdirmə"),
                            ("equipment", "Avadanlıq"),
                            ("access", "Giriş"),
                            ("training", "Təlim"),
                            ("orientation", "Orientasiya"),
                            ("other", "Digər"),
                        ],
                        default="documentation",
                        max_length=100,
                        verbose_name="Kateqoriya",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("in_progress", "Davam Edir"),
                            ("completed", "Tamamlanıb"),
                            ("skipped", "Ötürülüb"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarix"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarixi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_tasks",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_onboarding_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təyin Edilən",
                    ),
                ),
                (
                    "new_hire",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yeni İşçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İşəbaşlama Tapşırığı",
                "verbose_name_plural": "İşəbaşlama Tapşırıqları",
                "ordering": ["due_date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "status"],
                        name="recruitment_applica_0df70b_idx",
                    ),
                    models.Index(
                        fields=["new_hire", "status"],
                        name="recruitment_new_hir_e2a548_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "status"],
                        name="recruitment_assigne_0396c4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_title",
                    models.CharField(max_length=200, verbose_name="Vəzifə Adı"),
                ),
                (
                    "salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Maaş"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "bonus_potential",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Bonus Potensialı",
                    ),
                ),
                ("benefits", models.TextField(blank=True, verbose_name="Müavinətlər")),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlanğıc Tarixi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("sent", "Göndərildi"),
                            ("accepted", "Qəbul Edildi"),
                            ("rejected", "Rədd Edildi"),
                            ("negotiating", "Müzakirə Edilir"),
                            ("expired", "Müddəti Keçib"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "sent_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Göndərilmə Tarixi"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Qəbul Tarixi"
                    ),
                ),
                (
                    "response_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Cavab Tarixi"
                    ),
                ),
                (
                    "offer_letter",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="offer_letters/%Y/%m/",
                        verbose_name="Təklif Məktubu",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_offers",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Təklif",
                "verbose_name_plural": "Təkliflər",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["application", "status"],
                        name="recruitment_applica_f9f2e4_idx",
                    ),
                    models.Index(
                        fields=["status"], name="recruitment_status_c9d751_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["status", "posted_date"], name="recruitment_status_84e609_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["department"], name="recruitment_departm_94a2e0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobposting",
            index=models.Index(
                fields=["employment_type"], name="recruitment_employm_87e973_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["application", "status"], name="recruitment_applica_d3ac81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["scheduled_date"], name="recruitment_schedul_9f7e08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["job_posting", "status"], name="recruitment_job_pos_99b759_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["email"], name="recruitment_email_9308cd_idx"),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["status"], name="recruitment_status_d5b0c5_idx"),
        ),
    ]
