# Generated by Django 4.2.23 on 2025-10-21 21:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recruitment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalReferral",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        help_text="Namizədlə əlaqə (məs: Keçmiş həmkar, Universitet dostu)",
                        max_length=100,
                        verbose_name="Əlaqə",
                    ),
                ),
                (
                    "referral_notes",
                    models.TextField(blank=True, verbose_name="Tövsiyə Qeydləri"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Təqdim Edildi"),
                            ("under_review", "Baxışdadır"),
                            ("interview_scheduled", "Müsahibə Planlaşdırılıb"),
                            ("hired", "İşə Qəbul Edildi"),
                            ("not_selected", "Seçilmədi"),
                            ("withdrawn", "Geri Çəkildi"),
                        ],
                        default="submitted",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reward_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("eligible", "Uyğundur"),
                            ("approved", "Təsdiqləndi"),
                            ("paid", "Ödənildi"),
                            ("not_eligible", "Uyğun Deyil"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Mükafat Statusu",
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Mükafat Məbləği",
                    ),
                ),
                (
                    "reward_currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "reward_paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mükafat Ödəniş Tarixi"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Təqdim Tarixi"
                    ),
                ),
                (
                    "hired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="İşə Qəbul Tarixi"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recruitment.jobposting",
                        verbose_name="Vakansiya",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tövsiyə Edən",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Tövsiyə",
                "verbose_name_plural": "historical Tövsiyələr",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCandidateExperience",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "touchpoint",
                    models.CharField(
                        choices=[
                            ("application", "Müraciət"),
                            ("screening", "İlkin Sınaq"),
                            ("interview", "Müsahibə"),
                            ("assessment", "Qiymətləndirmə"),
                            ("offer", "Təklif"),
                            ("onboarding", "İşə Başlama"),
                            ("rejection", "Rədd"),
                        ],
                        max_length=20,
                        verbose_name="Təmas Nöqtəsi",
                    ),
                ),
                (
                    "feedback_date",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Rəy Tarixi"
                    ),
                ),
                (
                    "overall_satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        verbose_name="Ümumi Məmnuniyyət",
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Kommunikasiya Qiyməti",
                    ),
                ),
                (
                    "process_clarity_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Proses Aydınlığı",
                    ),
                ),
                (
                    "timeliness_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Vaxtında Olma",
                    ),
                ),
                (
                    "professionalism_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Peşəkarlıq",
                    ),
                ),
                (
                    "positive_aspects",
                    models.TextField(blank=True, verbose_name="Pozitiv Aspektlər"),
                ),
                (
                    "improvement_areas",
                    models.TextField(
                        blank=True, verbose_name="Təkmilləşdirmə Sahələri"
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(blank=True, verbose_name="Əlavə Şərhlər"),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Başqalarına Tövsiyə Edər"
                    ),
                ),
                (
                    "nps_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0-10: Bu şirkətdə işləməyi dostlarınıza nə dərəcədə tövsiyə edərsiniz?",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="NPS Balı",
                    ),
                ),
                (
                    "survey_completed",
                    models.BooleanField(default=False, verbose_name="Sorğu Tamamlandı"),
                ),
                (
                    "survey_sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sorğu Göndərilmə Tarixi"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Namizəd Təcrübəsi",
                "verbose_name_plural": "historical Namizəd Təcrübələri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        help_text="Namizədlə əlaqə (məs: Keçmiş həmkar, Universitet dostu)",
                        max_length=100,
                        verbose_name="Əlaqə",
                    ),
                ),
                (
                    "referral_notes",
                    models.TextField(blank=True, verbose_name="Tövsiyə Qeydləri"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("submitted", "Təqdim Edildi"),
                            ("under_review", "Baxışdadır"),
                            ("interview_scheduled", "Müsahibə Planlaşdırılıb"),
                            ("hired", "İşə Qəbul Edildi"),
                            ("not_selected", "Seçilmədi"),
                            ("withdrawn", "Geri Çəkildi"),
                        ],
                        default="submitted",
                        max_length=25,
                        verbose_name="Status",
                    ),
                ),
                (
                    "reward_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("eligible", "Uyğundur"),
                            ("approved", "Təsdiqləndi"),
                            ("paid", "Ödənildi"),
                            ("not_eligible", "Uyğun Deyil"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Mükafat Statusu",
                    ),
                ),
                (
                    "reward_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Mükafat Məbləği",
                    ),
                ),
                (
                    "reward_currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "reward_paid_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Mükafat Ödəniş Tarixi"
                    ),
                ),
                (
                    "submitted_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Təqdim Tarixi"
                    ),
                ),
                (
                    "hired_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="İşə Qəbul Tarixi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_info",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals",
                        to="recruitment.jobposting",
                        verbose_name="Vakansiya",
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tövsiyə Edən",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tövsiyə",
                "verbose_name_plural": "Tövsiyələr",
                "ordering": ["-submitted_date"],
                "indexes": [
                    models.Index(
                        fields=["referrer", "status"],
                        name="recruitment_referre_63ac71_idx",
                    ),
                    models.Index(
                        fields=["job_posting", "status"],
                        name="recruitment_job_pos_5a5693_idx",
                    ),
                    models.Index(
                        fields=["reward_status"], name="recruitment_reward__6615b2_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CandidateExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "touchpoint",
                    models.CharField(
                        choices=[
                            ("application", "Müraciət"),
                            ("screening", "İlkin Sınaq"),
                            ("interview", "Müsahibə"),
                            ("assessment", "Qiymətləndirmə"),
                            ("offer", "Təklif"),
                            ("onboarding", "İşə Başlama"),
                            ("rejection", "Rədd"),
                        ],
                        max_length=20,
                        verbose_name="Təmas Nöqtəsi",
                    ),
                ),
                (
                    "feedback_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Rəy Tarixi"),
                ),
                (
                    "overall_satisfaction",
                    models.IntegerField(
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        verbose_name="Ümumi Məmnuniyyət",
                    ),
                ),
                (
                    "communication_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Kommunikasiya Qiyməti",
                    ),
                ),
                (
                    "process_clarity_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Proses Aydınlığı",
                    ),
                ),
                (
                    "timeliness_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Vaxtında Olma",
                    ),
                ),
                (
                    "professionalism_rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Çox Narazı"),
                            (2, "Narazı"),
                            (3, "Neytral"),
                            (4, "Razı"),
                            (5, "Çox Razı"),
                        ],
                        null=True,
                        verbose_name="Peşəkarlıq",
                    ),
                ),
                (
                    "positive_aspects",
                    models.TextField(blank=True, verbose_name="Pozitiv Aspektlər"),
                ),
                (
                    "improvement_areas",
                    models.TextField(
                        blank=True, verbose_name="Təkmilləşdirmə Sahələri"
                    ),
                ),
                (
                    "additional_comments",
                    models.TextField(blank=True, verbose_name="Əlavə Şərhlər"),
                ),
                (
                    "would_recommend",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Başqalarına Tövsiyə Edər"
                    ),
                ),
                (
                    "nps_score",
                    models.IntegerField(
                        blank=True,
                        help_text="0-10: Bu şirkətdə işləməyi dostlarınıza nə dərəcədə tövsiyə edərsiniz?",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="NPS Balı",
                    ),
                ),
                (
                    "survey_completed",
                    models.BooleanField(default=False, verbose_name="Sorğu Tamamlandı"),
                ),
                (
                    "survey_sent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Sorğu Göndərilmə Tarixi"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experience_feedback",
                        to="recruitment.application",
                        verbose_name="Müraciət",
                    ),
                ),
            ],
            options={
                "verbose_name": "Namizəd Təcrübəsi",
                "verbose_name_plural": "Namizəd Təcrübələri",
                "ordering": ["-feedback_date"],
                "indexes": [
                    models.Index(
                        fields=["application", "touchpoint"],
                        name="recruitment_applica_309183_idx",
                    ),
                    models.Index(
                        fields=["touchpoint", "overall_satisfaction"],
                        name="recruitment_touchpo_700915_idx",
                    ),
                ],
            },
        ),
    ]
