# Generated by Django 5.1.4 on 2026-07-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_historicalreferral_historicalcandidateexperience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-poçt')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('skills', models.TextField(blank=True, verbose_name='Bilik və Bacarıqlar')),
                ('resume', models.FileField(blank=True, null=True, upload_to='talent_pool/', verbose_name='CV/Rezume')),
                ('source', models.CharField(blank=True, max_length=50, verbose_name='Mənbə')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Əlavə Edilmə Tarixi')),
            ],
            options={
                'verbose_name': 'Talent Pool Namizədi',
                'verbose_name_plural': 'Talent Pool',
            },
        ),
    ]
