# Generated by Django 5.1.4 on 2026-07-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'verbose_name': 'Siyasət', 'verbose_name_plural': 'Siyasətlər'},
        ),
        migrations.AlterModelOptions(
            name='policyversion',
            options={'verbose_name': 'Siyasət Versiyası', 'verbose_name_plural': 'Siyasət Versiyaları'},
        ),
        migrations.AlterField(
            model_name='policy',
            name='category',
            field=models.CharField(choices=[('HR', 'İnsan Resursları'), ('IT', 'İnformasiya Texnologiyaları'), ('FINANCE', 'Maliyyə'), ('SECURITY', 'Təhlükəsizlik'), ('COMPLIANCE', 'Uyğunluq'), ('GENERAL', 'Ümumi')], default='GENERAL', max_length=100, verbose_name='Kateqoriya'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Siyasət adı'),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktiv versiya'),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policy_engine.policy', verbose_name='Siyasət'),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='rule_json',
            field=models.JSONField(blank=True, default=dict, help_text='Təşkilati siyasət qaydalarını JSONLogic formatında daxil edin. Məsələn: {"if": [{">": [{"var": "leave_days"}, 5]}, "requires_approval", "auto_approve"]}', verbose_name='Siyasət qaydaları (JSON)'),
        ),
        migrations.AlterField(
            model_name='policyversion',
            name='version_number',
            field=models.PositiveIntegerField(verbose_name='Versiya nömrəsi'),
        ),
    ]
