# Generated by Django 5.1.4 on 2026-07-14 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_engine', '0002_alter_policy_options_alter_policyversion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100, verbose_name='Əməliyyat')),
                ('actor', models.CharField(max_length=100, verbose_name='İcraçı')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detallar')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='policy_engine.policy', verbose_name='Siyasət')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy_engine.policyversion', verbose_name='Versiya')),
            ],
            options={
                'verbose_name': 'Siyasət Jurnalı',
                'verbose_name_plural': 'Siyasət Jurnalları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Qayda adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıqlama')),
                ('condition_json', models.JSONField(blank=True, default=dict, verbose_name='Şərt (JSON)')),
                ('action_json', models.JSONField(blank=True, default=dict, verbose_name='Nəticə (JSON)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='İcra sırası')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='policy_engine.policyversion', verbose_name='Versiya')),
            ],
            options={
                'verbose_name': 'Siyasət Qaydası',
                'verbose_name_plural': 'Siyasət Qaydaları',
                'ordering': ['order'],
            },
        ),
    ]
