# Generated by Django 5.1.4 on 2025-10-17 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0012_remove_department_departments_department_tref4ab"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Widget Name")),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("realtime_stats", "Real-time Statistics"),
                            ("kpi_summary", "KPI Summary"),
                            ("trend_analysis", "Trend Analysis"),
                            ("forecasting", "Forecasting"),
                            ("heatmap", "Heatmap"),
                            ("line_chart", "Line Chart"),
                            ("bar_chart", "Bar Chart"),
                            ("radar_chart", "Radar Chart"),
                        ],
                        max_length=20,
                        verbose_name="Widget Type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Display Order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Configuration"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SystemKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="KPI Name")),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("overall", "Overall Performance"),
                            ("salary", "Salary Trends"),
                            ("hiring", "Hiring Trends"),
                            ("performance", "Performance Trends"),
                            ("staffing", "Staffing Forecast"),
                            ("budget", "Budget Forecast"),
                        ],
                        max_length=20,
                        verbose_name="KPI Type",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Value"
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Target",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="%", max_length=20, verbose_name="Unit"),
                ),
                ("period_start", models.DateTimeField(verbose_name="Period Start")),
                ("period_end", models.DateTimeField(verbose_name="Period End")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "System KPI",
                "verbose_name_plural": "System KPIs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Report Name")),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("kpi_summary", "KPI Summary"),
                            ("trend_analysis", "Trend Analysis"),
                            ("forecast", "Forecast Report"),
                            ("comparative", "Comparative Analysis"),
                            ("departmental", "Departmental Analysis"),
                        ],
                        max_length=20,
                        verbose_name="Report Type",
                    ),
                ),
                ("data", models.JSONField(default=dict, verbose_name="Report Data")),
                ("start_date", models.DateTimeField(verbose_name="Start Date")),
                ("end_date", models.DateTimeField(verbose_name="End Date")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Is Published"),
                ),
                (
                    "file_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="File Path"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generated By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analytics Report",
                "verbose_name_plural": "Analytics Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stat_type",
                    models.CharField(
                        choices=[
                            ("active_users", "Active Users"),
                            ("pending_evaluations", "Pending Evaluations"),
                            ("new_hires", "New Hires"),
                            ("avg_performance", "Average Performance"),
                            ("budget_utilization", "Budget Utilization"),
                            ("leave_requests", "Leave Requests"),
                            ("training_completions", "Training Completions"),
                        ],
                        max_length=30,
                        verbose_name="Stat Type",
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Current Value"
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Previous Value",
                    ),
                ),
                (
                    "unit",
                    models.CharField(default="", max_length=20, verbose_name="Unit"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Description"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Real-time Stat",
                "verbose_name_plural": "Real-time Stats",
                "ordering": ["stat_type"],
            },
        ),
        migrations.CreateModel(
            name="ForecastData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[
                            ("staffing", "Staffing"),
                            ("budget", "Budget"),
                            ("performance", "Performance"),
                            ("hiring", "Hiring"),
                        ],
                        max_length=50,
                        verbose_name="Forecast Type",
                    ),
                ),
                ("forecast_date", models.DateField(verbose_name="Forecast Date")),
                (
                    "predicted_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Predicted Value"
                    ),
                ),
                (
                    "confidence_level",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="Confidence Level",
                    ),
                ),
                (
                    "actual_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=15,
                        null=True,
                        verbose_name="Actual Value",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, verbose_name="Explanation"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Forecast Data",
                "verbose_name_plural": "Forecast Data",
                "ordering": ["-forecast_date"],
                "unique_together": {
                    ("forecast_type", "forecast_date", "department", "organization")
                },
            },
        ),
        migrations.CreateModel(
            name="TrendData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("salary", "Salary"),
                            ("performance", "Performance"),
                            ("hiring", "Hiring"),
                            ("attendance", "Attendance"),
                            ("compensation", "Compensation"),
                        ],
                        max_length=50,
                        verbose_name="Data Type",
                    ),
                ),
                ("period", models.DateField(verbose_name="Period")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Value"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.department",
                        verbose_name="Department",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="departments.organization",
                        verbose_name="Organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend Data",
                "verbose_name_plural": "Trend Data",
                "ordering": ["-period"],
                "unique_together": {
                    ("data_type", "period", "department", "organization")
                },
            },
        ),
    ]
