# Generated by Django 5.1.4 on 2026-07-14 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(default='overview', max_length=50, verbose_name='Default View')),
                ('auto_refresh_interval', models.PositiveIntegerField(default=300, help_text='In seconds', verbose_name='Auto Refresh Interval')),
                ('theme_preference', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='system', max_length=20, verbose_name='Theme Preference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Dashboard Setting',
                'verbose_name_plural': 'Dashboard Settings',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('icon', models.CharField(default='fa-star', max_length=50, verbose_name='Icon Class')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Favorite Item',
                'verbose_name_plural': 'Favorite Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_x', models.PositiveIntegerField(default=0, verbose_name='Position X')),
                ('position_y', models.PositiveIntegerField(default=0, verbose_name='Position Y')),
                ('width', models.PositiveIntegerField(default=1, verbose_name='Width')),
                ('height', models.PositiveIntegerField(default=1, verbose_name='Height')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Is Visible')),
                ('custom_config', models.JSONField(blank=True, default=dict, verbose_name='Custom Configuration')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dashboardwidget', verbose_name='Widget')),
            ],
            options={
                'verbose_name': 'User Dashboard Widget',
                'verbose_name_plural': 'User Dashboard Widgets',
                'unique_together': {('user', 'widget')},
            },
        ),
    ]
