# Generated by Django 4.2.23 on 2025-10-21 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0005_evaluationcampaign_weight_peer_and_more"),
        ("continuous_feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quickfeedback",
            name="anonymous_hash",
            field=models.CharField(
                blank=True,
                help_text="Anonim feedbackin təkrarlanmasını yoxlamaq üçün hash",
                max_length=64,
                verbose_name="Anonim Hash",
            ),
        ),
        migrations.AddField(
            model_name="quickfeedback",
            name="feedback_campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="continuous_feedbacks",
                to="evaluations.evaluationcampaign",
                verbose_name="Qiymətləndirmə Kampaniyası",
            ),
        ),
        migrations.AddField(
            model_name="quickfeedback",
            name="is_part_of_360",
            field=models.BooleanField(
                default=False,
                help_text="Bu feedback 360-dərəcə qiymətləndirmənin bir hissəsidir",
                verbose_name="360° Feedback Parçası",
            ),
        ),
        migrations.AddField(
            model_name="quickfeedback",
            name="source_relationship",
            field=models.CharField(
                choices=[
                    ("self", "Özünüdəyərləndirmə"),
                    ("manager", "Menecer"),
                    ("peer", "Həmkar"),
                    ("direct_report", "Tabeli"),
                    ("cross_functional", "Kross-funksional"),
                    ("customer", "Müştəri"),
                    ("external", "Xarici"),
                ],
                default="peer",
                help_text="360-dərəcə feedback üçün göndərənin alıcı ilə əlaqəsi",
                max_length=20,
                verbose_name="Mənbə Əlaqəsi",
            ),
        ),
        migrations.AlterField(
            model_name="quickfeedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("recognition", "Təşəkkür / Recognition"),
                    ("improvement", "Təklif / Improvement"),
                    ("general", "Ümumi"),
                    ("behavioral", "Davranış"),
                    ("skill", "Bacarıq"),
                    ("leadership", "Liderlik"),
                ],
                max_length=20,
                verbose_name="Rəy Tipi",
            ),
        ),
    ]
