# Generated by Django 5.1.4 on 2026-07-14 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_feedback', '0002_quickfeedback_anonymous_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackbank',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Orta Qiymət'),
        ),
        migrations.AlterField(
            model_name='feedbackbank',
            name='positive_sentiment_score',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Müsbət Sentiment Balı'),
        ),
        migrations.AlterField(
            model_name='feedbackbank',
            name='total_feedbacks_received',
            field=models.IntegerField(blank=True, default=0, verbose_name='Alınan Ümumi Rəylər'),
        ),
        migrations.AlterField(
            model_name='feedbackbank',
            name='total_improvements',
            field=models.IntegerField(blank=True, default=0, verbose_name='Alınan Təkliflər'),
        ),
        migrations.AlterField(
            model_name='feedbackbank',
            name='total_recognitions',
            field=models.IntegerField(blank=True, default=0, verbose_name='Alınan Təşəkkürlər'),
        ),
    ]
