# Generated by Django 5.1.4 on 2026-07-14 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('continuous_feedback', '0003_alter_feedbackbank_average_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Şablon Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('content_template', models.TextField(verbose_name='Şablon Məzmunu')),
                ('feedback_type', models.CharField(choices=[('recognition', 'Təşəkkür / Recognition'), ('improvement', 'Təklif / Improvement'), ('general', 'Ümumi'), ('behavioral', 'Davranış'), ('skill', 'Bacarıq'), ('leadership', 'Liderlik')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rəy Şablonu',
                'verbose_name_plural': 'Rəy Şablonları',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(blank=True)),
                ('remind_at', models.DateTimeField(verbose_name='Xatırlatma Vaxtı')),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rəy Xatırlatması',
                'verbose_name_plural': 'Rəy Xatırlatmaları',
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Mövzu')),
                ('message', models.TextField(blank=True, verbose_name='Mesaj')),
                ('status', models.CharField(choices=[('pending', 'Gözləyir'), ('completed', 'Tamamlandı'), ('declined', 'Rədd edildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rəy Sorğusu',
                'verbose_name_plural': 'Rəy Sorğuları',
                'ordering': ['-created_at'],
            },
        ),
    ]
