# Generated by Django 4.2.23 on 2025-10-09 06:28

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("manager", "Menecer"),
                            ("employee", "İşçi"),
                        ],
                        default="employee",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="Vəzifə"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Ata adı"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="İşçi ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="Profil Şəkli",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Haqqında")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Qoşulma Tarixi"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Giriş"
                    ),
                ),
            ],
            options={
                "verbose_name": "İstifadəçi",
                "verbose_name_plural": "İstifadəçilər",
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarixi"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="İşə Qəbul Tarixi"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Təhsil Səviyyəsi"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="İxtisas"
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="İş E-poçtu"
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="İş Telefonu"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Ünvan")),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("az", "Azərbaycan"),
                            ("en", "English"),
                            ("ru", "Русский"),
                        ],
                        default="az",
                        max_length=10,
                        verbose_name="Dil Seçimi",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="E-poçt Bildirişləri"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=False, verbose_name="SMS Bildirişləri"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Profil",
                "verbose_name_plural": "historical Profillər",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalRole",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("manager", "Menecer"),
                            ("employee", "İşçi"),
                        ],
                        db_index=True,
                        max_length=50,
                        verbose_name="Rol Adı",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Göstəriləcək Ad"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Rol",
                "verbose_name_plural": "historical Rollar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalUser",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True,
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("manager", "Menecer"),
                            ("employee", "İşçi"),
                        ],
                        default="employee",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=100, verbose_name="Vəzifə"),
                ),
                (
                    "middle_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Ata adı"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=50,
                        null=True,
                        verbose_name="İşçi ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Profil Şəkli",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="Haqqında")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "date_joined",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Qoşulma Tarixi"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son Giriş"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical İstifadəçi",
                "verbose_name_plural": "historical İstifadəçilər",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("superadmin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("manager", "Menecer"),
                            ("employee", "İşçi"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Rol Adı",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Göstəriləcək Ad"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="custom_roles",
                        to="auth.permission",
                        verbose_name="İcazələr",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Rollar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Doğum Tarixi"
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="İşə Qəbul Tarixi"
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Təhsil Səviyyəsi"
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="İxtisas"
                    ),
                ),
                (
                    "work_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="İş E-poçtu"
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="İş Telefonu"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Ünvan")),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("az", "Azərbaycan"),
                            ("en", "English"),
                            ("ru", "Русский"),
                        ],
                        default="az",
                        max_length=10,
                        verbose_name="Dil Seçimi",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="E-poçt Bildirişləri"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=False, verbose_name="SMS Bildirişləri"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profil",
                "verbose_name_plural": "Profillər",
            },
        ),
    ]
