# Generated by Django 4.2.23 on 2025-10-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0011_department_departments_department_tref4ab"),
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Şəhər"),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="contract_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Müqavilə Bitmə Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="contract_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Müqavilə Başlanğıc Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("permanent", "Daimi"),
                    ("temporary", "Müvəqqəti"),
                    ("contract", "Müqavilə"),
                    ("probation", "Sınaq Müddəti"),
                ],
                default="permanent",
                max_length=50,
                verbose_name="Müqavilə Növü",
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Fövqəladə Əlaqə Adı"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Fövqəladə Əlaqə Telefonu"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Qohumluq Əlaqəsi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="graduation_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Məzuniyyət İli"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="health_insurance_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tibbi Sığorta Nömrəsi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="health_insurance_provider",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tibbi Sığorta Təminatçısı"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Subay"),
                    ("married", "Evli"),
                    ("divorced", "Boşanmış"),
                    ("widowed", "Dul"),
                ],
                max_length=20,
                verbose_name="Ailə Vəziyyəti",
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Şəxsiyyət Vəsiqəsi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Vətəndaşlıq"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="number_of_children",
            field=models.PositiveIntegerField(default=0, verbose_name="Uşaq Sayı"),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="pension_insurance_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Pensiya Sığortası Nömrəsi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="personal_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Şəxsi E-poçt"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="personal_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Şəxsi Telefon"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Doğum Yeri"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Poçt Kodu"),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="probation_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Sınaq Müddəti Bitmə Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Vergi Nömrəsi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="termination_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="İşdən Çıxma Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="termination_reason",
            field=models.TextField(blank=True, verbose_name="İşdən Çıxma Səbəbi"),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="university",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Universitet"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Şəhər"),
        ),
        migrations.AddField(
            model_name="profile",
            name="contract_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Müqavilə Bitmə Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="contract_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Müqavilə Başlanğıc Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="contract_type",
            field=models.CharField(
                choices=[
                    ("permanent", "Daimi"),
                    ("temporary", "Müvəqqəti"),
                    ("contract", "Müqavilə"),
                    ("probation", "Sınaq Müddəti"),
                ],
                default="permanent",
                max_length=50,
                verbose_name="Müqavilə Növü",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_name",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Fövqəladə Əlaqə Adı"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Fövqəladə Əlaqə Telefonu"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="emergency_contact_relationship",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Qohumluq Əlaqəsi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="graduation_year",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Məzuniyyət İli"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="health_insurance_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Tibbi Sığorta Nömrəsi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="health_insurance_provider",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Tibbi Sığorta Təminatçısı"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="marital_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("single", "Subay"),
                    ("married", "Evli"),
                    ("divorced", "Boşanmış"),
                    ("widowed", "Dul"),
                ],
                max_length=20,
                verbose_name="Ailə Vəziyyəti",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="national_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Şəxsiyyət Vəsiqəsi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Vətəndaşlıq"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="number_of_children",
            field=models.PositiveIntegerField(default=0, verbose_name="Uşaq Sayı"),
        ),
        migrations.AddField(
            model_name="profile",
            name="pension_insurance_number",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Pensiya Sığortası Nömrəsi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Şəxsi E-poçt"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="personal_phone",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Şəxsi Telefon"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="place_of_birth",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Doğum Yeri"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="Poçt Kodu"),
        ),
        migrations.AddField(
            model_name="profile",
            name="probation_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Sınaq Müddəti Bitmə Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="tax_id",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Vergi Nömrəsi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="termination_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="İşdən Çıxma Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="termination_reason",
            field=models.TextField(blank=True, verbose_name="İşdən Çıxma Səbəbi"),
        ),
        migrations.AddField(
            model_name="profile",
            name="university",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Universitet"
            ),
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "Orta Məktəb"),
                    ("vocational", "Texniki"),
                    ("bachelor", "Bakalavr"),
                    ("master", "Magistr"),
                    ("phd", "PhD/Doktorantura"),
                ],
                max_length=100,
                verbose_name="Təhsil Səviyyəsi",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high_school", "Orta Məktəb"),
                    ("vocational", "Texniki"),
                    ("bachelor", "Bakalavr"),
                    ("master", "Magistr"),
                    ("phd", "PhD/Doktorantura"),
                ],
                max_length=100,
                verbose_name="Təhsil Səviyyəsi",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWorkHistory",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("hire", "İşə Qəbul"),
                            ("promotion", "Vəzifə Dəyişikliyi (Tərtiqə)"),
                            ("transfer", "Şöbə Köçürülməsi"),
                            ("salary_adjustment", "Maaş Düzəlişi"),
                            ("termination", "İşdən Çıxma"),
                            ("other", "Digər"),
                        ],
                        max_length=50,
                        verbose_name="Dəyişiklik Növü",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(verbose_name="Qüvvəyə Minmə Tarixi"),
                ),
                (
                    "old_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Əvvəlki Vəzifə"
                    ),
                ),
                (
                    "new_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Yeni Vəzifə"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Səbəb")),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="departments.department",
                        verbose_name="Yeni Şöbə",
                    ),
                ),
                (
                    "old_department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="departments.department",
                        verbose_name="Əvvəlki Şöbə",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical İş Tarixçəsi",
                "verbose_name_plural": "historical İş Tarixçələri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "Şəxsiyyət Vəsiqəsi"),
                            ("passport", "Pasport"),
                            ("resume", "CV/Rezume"),
                            ("diploma", "Diplom"),
                            ("certificate", "Sertifikat"),
                            ("contract", "Əmək Müqaviləsi"),
                            ("termination", "İşdən Çıxma Sənədi"),
                            ("medical", "Tibbi Sənəd"),
                            ("police_clearance", "Məhkumsuzluq Arayışı"),
                            ("other", "Digər"),
                        ],
                        max_length=50,
                        verbose_name="Sənəd Növü",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("file", models.TextField(max_length=100, verbose_name="Fayl")),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fayl Ölçüsü (bytes)"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Verilmə Tarixi"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitmə Tarixi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükləyən",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical İşçi Sənədi",
                "verbose_name_plural": "historical İşçi Sənədləri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="WorkHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("hire", "İşə Qəbul"),
                            ("promotion", "Vəzifə Dəyişikliyi (Tərtiqə)"),
                            ("transfer", "Şöbə Köçürülməsi"),
                            ("salary_adjustment", "Maaş Düzəlişi"),
                            ("termination", "İşdən Çıxma"),
                            ("other", "Digər"),
                        ],
                        max_length=50,
                        verbose_name="Dəyişiklik Növü",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(verbose_name="Qüvvəyə Minmə Tarixi"),
                ),
                (
                    "old_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Əvvəlki Vəzifə"
                    ),
                ),
                (
                    "new_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Yeni Vəzifə"
                    ),
                ),
                ("reason", models.TextField(blank=True, verbose_name="Səbəb")),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_work_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_work_histories",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "new_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_work_histories",
                        to="departments.department",
                        verbose_name="Yeni Şöbə",
                    ),
                ),
                (
                    "old_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_work_histories",
                        to="departments.department",
                        verbose_name="Əvvəlki Şöbə",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İş Tarixçəsi",
                "verbose_name_plural": "İş Tarixçələri",
                "ordering": ["-effective_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "effective_date"],
                        name="accounts_wo_user_id_1de8f0_idx",
                    ),
                    models.Index(
                        fields=["change_type"], name="accounts_wo_change__ba220f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EmployeeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("id_card", "Şəxsiyyət Vəsiqəsi"),
                            ("passport", "Pasport"),
                            ("resume", "CV/Rezume"),
                            ("diploma", "Diplom"),
                            ("certificate", "Sertifikat"),
                            ("contract", "Əmək Müqaviləsi"),
                            ("termination", "İşdən Çıxma Sənədi"),
                            ("medical", "Tibbi Sənəd"),
                            ("police_clearance", "Məhkumsuzluq Arayışı"),
                            ("other", "Digər"),
                        ],
                        max_length=50,
                        verbose_name="Sənəd Növü",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "file",
                    models.FileField(
                        upload_to="employee_documents/%Y/%m/", verbose_name="Fayl"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Fayl Ölçüsü (bytes)"
                    ),
                ),
                (
                    "issue_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Verilmə Tarixi"
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitmə Tarixi"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükləyən",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İşçi Sənədi",
                "verbose_name_plural": "İşçi Sənədləri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "document_type"],
                        name="accounts_em_user_id_92a11b_idx",
                    ),
                    models.Index(
                        fields=["expiry_date"], name="accounts_em_expiry__df6ac5_idx"
                    ),
                ],
            },
        ),
    ]
