# Generated by Django 5.1.4 on 2025-10-17 18:53

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_historicalprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.Q360UserManager()),
            ],
        ),
    ]
