# Generated by Django 5.1.4 on 2025-10-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_usermfaconfig"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprofile",
            name="two_factor_backup_codes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="2FA Backup Kodları"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Aktiv"),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="two_factor_enabled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="2FA Aktivləşdirmə Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="historicalprofile",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="2FA Secret"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_factor_backup_codes",
            field=models.JSONField(
                blank=True, default=list, verbose_name="2FA Backup Kodları"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_factor_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Aktiv"),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_factor_enabled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="2FA Aktivləşdirmə Tarixi"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="two_factor_secret",
            field=models.CharField(
                blank=True, max_length=32, null=True, verbose_name="2FA Secret"
            ),
        ),
    ]
