# Generated by Django 5.1.4 on 2026-07-14 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_historicalprofile_two_factor_backup_codes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('admin', 'Administrator'), ('hr', 'İnsan Resursları'), ('manager', 'Menecer'), ('employee', 'İşçi')], default='employee', max_length=20, verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrator'), ('admin', 'Administrator'), ('hr', 'İnsan Resursları'), ('manager', 'Menecer'), ('employee', 'İşçi')], default='employee', max_length=20, verbose_name='Rol'),
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('token_prefix', models.CharField(max_length=12, verbose_name='Token prefiksi')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Token hash')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='Son istifadə')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Bitmə tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokenlər',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('system', 'Sistem'), ('light', 'İşıqlı'), ('dark', 'Qaranlıq')], default='system', max_length=10, verbose_name='Tema')),
                ('density', models.CharField(choices=[('comfortable', 'Rahat'), ('compact', 'Yığcam')], default='comfortable', max_length=15, verbose_name='Sıxlıq')),
                ('language', models.CharField(default='az', max_length=10, verbose_name='Dil')),
                ('timezone_name', models.CharField(default='Asia/Baku', max_length=50, verbose_name='Saat qurşağı')),
                ('notify_email', models.BooleanField(default=True, verbose_name='E-poçt bildirişləri')),
                ('notify_sms', models.BooleanField(default=False, verbose_name='SMS bildirişləri')),
                ('notify_push', models.BooleanField(default=True, verbose_name='Push bildirişləri')),
                ('digest_frequency', models.CharField(choices=[('none', 'Heç vaxt'), ('daily', 'Günlük'), ('weekly', 'Həftəlik')], default='daily', max_length=10, verbose_name='Xülasə tezliyi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preferences', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'İstifadəçi Seçimi',
                'verbose_name_plural': 'İstifadəçi Seçimləri',
            },
        ),
    ]
