# Generated by Django 5.1.4 on 2026-07-14 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_historicaluser_role_alter_user_role_apitoken_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Avadanlıq Adı')),
                ('asset_id', models.CharField(max_length=100, verbose_name='İnventar Nömrəsi')),
                ('assigned_date', models.DateField(verbose_name='Verilmə Tarixi')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Qaytarılma Tarixi')),
                ('status', models.CharField(choices=[('ASSIGNED', 'İstifadədə'), ('RETURNED', 'Qaytarılıb'), ('LOST', 'İtib')], max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Avadanlıq',
                'verbose_name_plural': 'Avadanlıqlar',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=100, verbose_name='Müqavilə Nömrəsi')),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Daimi'), ('FIXED_TERM', 'Müddətli'), ('INTERN', 'Təcrübəçi')], max_length=100, verbose_name='Müqavilə Növü')),
                ('start_date', models.DateField(verbose_name='Başlama Tarixi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitmə Tarixi')),
                ('file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Müqavilə Faylı')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Müqavilə',
                'verbose_name_plural': 'Müqavilələr',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('relationship', models.CharField(max_length=100, verbose_name='Qohumluq Əlaqəsi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Əsas Əlaqə')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Fövqəladə Əlaqə',
                'verbose_name_plural': 'Fövqəladə Əlaqələr',
            },
        ),
    ]
