# Generated by Django 5.1.4 on 2025-10-11 07:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competencies", "0001_initial"),
        ("development_plans", "0005_remove_is_approved_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTrainingResource",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Təlim Adı")),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course", "Kurs"),
                            ("certification", "Sertifikasiya"),
                            ("mentoring", "Mentorluq"),
                            ("workshop", "Seminar"),
                            ("conference", "Konfrans"),
                            ("webinar", "Vebinar"),
                            ("self_study", "Öz-özünə Təhsil"),
                        ],
                        default="course",
                        max_length=20,
                        verbose_name="Təlim Növü",
                    ),
                ),
                ("is_online", models.BooleanField(default=True, verbose_name="Onlayn")),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("online", "Onlayn"),
                            ("offline", "Oflayn"),
                            ("hybrid", "Hibrid"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Çatdırılma Metodu",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Onlayn təlim linki və ya əlavə məlumat",
                        verbose_name="Link",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Başlanğıc"),
                            ("intermediate", "Orta"),
                            ("advanced", "Təkmil"),
                            ("expert", "Ekspert"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="Çətinlik Səviyyəsi",
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Təlimin təxmini müddəti saat olaraq",
                        max_digits=6,
                        null=True,
                        verbose_name="Müddət (saat)",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="Azərbaycan", max_length=50, verbose_name="Dil"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Təlim Təminatçısı"
                    ),
                ),
                (
                    "instructor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Təlimatçı/Mütəxəssis"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Təlimin dəyəri (manat)",
                        max_digits=10,
                        null=True,
                        verbose_name="Qiymət",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum İştirakçı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Müəyyən vəzifələr üçün məcburi təlim",
                        verbose_name="Məcburi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Təlim Resursu",
                "verbose_name_plural": "historical Təlim Resursları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TrainingResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, verbose_name="Təlim Adı")),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("course", "Kurs"),
                            ("certification", "Sertifikasiya"),
                            ("mentoring", "Mentorluq"),
                            ("workshop", "Seminar"),
                            ("conference", "Konfrans"),
                            ("webinar", "Vebinar"),
                            ("self_study", "Öz-özünə Təhsil"),
                        ],
                        default="course",
                        max_length=20,
                        verbose_name="Təlim Növü",
                    ),
                ),
                ("is_online", models.BooleanField(default=True, verbose_name="Onlayn")),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("online", "Onlayn"),
                            ("offline", "Oflayn"),
                            ("hybrid", "Hibrid"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="Çatdırılma Metodu",
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Onlayn təlim linki və ya əlavə məlumat",
                        verbose_name="Link",
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Başlanğıc"),
                            ("intermediate", "Orta"),
                            ("advanced", "Təkmil"),
                            ("expert", "Ekspert"),
                        ],
                        default="intermediate",
                        max_length=20,
                        verbose_name="Çətinlik Səviyyəsi",
                    ),
                ),
                (
                    "duration_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Təlimin təxmini müddəti saat olaraq",
                        max_digits=6,
                        null=True,
                        verbose_name="Müddət (saat)",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="Azərbaycan", max_length=50, verbose_name="Dil"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Təlim Təminatçısı"
                    ),
                ),
                (
                    "instructor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Təlimatçı/Mütəxəssis"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Təlimin dəyəri (manat)",
                        max_digits=10,
                        null=True,
                        verbose_name="Qiymət",
                    ),
                ),
                (
                    "max_participants",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum İştirakçı"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Müəyyən vəzifələr üçün məcburi təlim",
                        verbose_name="Məcburi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "required_competencies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Bu təlimin inkişaf etdirdiyi kompetensiyalar",
                        related_name="training_resources",
                        to="competencies.competency",
                        verbose_name="Əlaqəli Kompetensiyalar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Təlim Resursu",
                "verbose_name_plural": "Təlim Resursları",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalUserTraining",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("self_enrolled", "Özü Qeydiyyatdan Keçdi"),
                            ("manager_assigned", "Menecer Tərəfindən Təyin Edildi"),
                            ("system_recommended", "Sistem Tövsiyəsi"),
                            ("mandatory", "Məcburi"),
                        ],
                        default="self_enrolled",
                        max_length=30,
                        verbose_name="Təyin Növü",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlama Tarixi"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarix"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarixi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("in_progress", "Davam Edir"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "Ləğv Edildi"),
                            ("failed", "Uğursuz"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="0-100 arası", verbose_name="Proqres (%)"
                    ),
                ),
                (
                    "completion_note",
                    models.TextField(blank=True, verbose_name="Tamamlanma Qeydi"),
                ),
                (
                    "user_feedback",
                    models.TextField(blank=True, verbose_name="İstifadəçi Rəyi"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5 ulduz arası qiymətləndirmə",
                        null=True,
                        verbose_name="Reytinq",
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(blank=True, verbose_name="Sertifikat Linki"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təyin Edən",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_goal",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="development_plans.developmentgoal",
                        verbose_name="Əlaqəli İnkişaf Məqsədi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.trainingresource",
                        verbose_name="Təlim Resursu",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical İstifadəçi Təlimi",
                "verbose_name_plural": "historical İstifadəçi Təlimləri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="UserTraining",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("self_enrolled", "Özü Qeydiyyatdan Keçdi"),
                            ("manager_assigned", "Menecer Tərəfindən Təyin Edildi"),
                            ("system_recommended", "Sistem Tövsiyəsi"),
                            ("mandatory", "Məcburi"),
                        ],
                        default="self_enrolled",
                        max_length=30,
                        verbose_name="Təyin Növü",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Başlama Tarixi"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Son Tarix"),
                ),
                (
                    "completed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarixi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("in_progress", "Davam Edir"),
                            ("completed", "Tamamlandı"),
                            ("cancelled", "Ləğv Edildi"),
                            ("failed", "Uğursuz"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "progress_percentage",
                    models.IntegerField(
                        default=0, help_text="0-100 arası", verbose_name="Proqres (%)"
                    ),
                ),
                (
                    "completion_note",
                    models.TextField(blank=True, verbose_name="Tamamlanma Qeydi"),
                ),
                (
                    "user_feedback",
                    models.TextField(blank=True, verbose_name="İstifadəçi Rəyi"),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        help_text="1-5 ulduz arası qiymətləndirmə",
                        null=True,
                        verbose_name="Reytinq",
                    ),
                ),
                (
                    "certificate_url",
                    models.URLField(blank=True, verbose_name="Sertifikat Linki"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_trainings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təyin Edən",
                    ),
                ),
                (
                    "related_goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_trainings",
                        to="development_plans.developmentgoal",
                        verbose_name="Əlaqəli İnkişaf Məqsədi",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trainings",
                        to="training.trainingresource",
                        verbose_name="Təlim Resursu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_trainings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İstifadəçi Təlimi",
                "verbose_name_plural": "İstifadəçi Təlimləri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trainingresource",
            index=models.Index(
                fields=["type", "is_active"], name="training_tr_type_38fb0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingresource",
            index=models.Index(
                fields=["difficulty_level"], name="training_tr_difficu_3024b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingresource",
            index=models.Index(
                fields=["is_mandatory"], name="training_tr_is_mand_e6b83e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertraining",
            index=models.Index(
                fields=["user", "status"], name="training_us_user_id_4bff29_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertraining",
            index=models.Index(
                fields=["resource", "status"], name="training_us_resourc_c03d3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertraining",
            index=models.Index(
                fields=["due_date"], name="training_us_due_dat_898bb2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertraining",
            index=models.Index(
                fields=["assignment_type"], name="training_us_assignm_b6e785_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usertraining",
            unique_together={("user", "resource")},
        ),
    ]
