# Generated by Django 5.1.4 on 2025-10-11 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencies", "0002_competency_competencie_name_eac81b_idx_and_more"),
        ("development_plans", "0005_remove_is_approved_field"),
        ("training", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="trainingresource",
            index=models.Index(
                fields=["provider"], name="training_tr_provide_516d62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trainingresource",
            index=models.Index(
                fields=["title", "type"], name="training_tr_title_f512b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertraining",
            index=models.Index(
                fields=["user", "resource", "status"],
                name="training_us_user_id_4c1bef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usertraining",
            index=models.Index(
                fields=["progress_percentage"], name="training_us_progres_290244_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usertraining",
            index=models.Index(fields=["rating"], name="training_us_rating_17dd9d_idx"),
        ),
    ]
