# Generated by Django 4.2.23 on 2025-10-21 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("competencies", "0002_competency_competencie_name_eac81b_idx_and_more"),
        ("training", "0002_trainingresource_training_tr_provide_516d62_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certification_name",
                    models.CharField(max_length=200, verbose_name="Sertifikat Adı"),
                ),
                (
                    "certification_code",
                    models.CharField(
                        blank=True,
                        help_text="Məsələn: PMP, AWS-SAA, CISSP",
                        max_length=100,
                        verbose_name="Sertifikat Kodu",
                    ),
                ),
                (
                    "issuing_organization",
                    models.CharField(
                        max_length=200, verbose_name="Təqdim Edən Təşkilat"
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sertifikat ID"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Verilmə Tarixi")),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitmə Tarixi"
                    ),
                ),
                (
                    "last_renewal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Yeniləmə Tarixi"
                    ),
                ),
                (
                    "renewal_frequency",
                    models.CharField(
                        choices=[
                            ("annual", "İllik"),
                            ("biennial", "2 İllik"),
                            ("triennial", "3 İllik"),
                            ("lifetime", "Ömürlük"),
                            ("custom", "Xüsusi"),
                        ],
                        default="annual",
                        max_length=20,
                        verbose_name="Yeniləmə Tezliyi",
                    ),
                ),
                (
                    "renewal_reminder_days",
                    models.IntegerField(
                        default=60,
                        help_text="Bitmə tarixindən neçə gün əvvəl xatırlatma göndərsin",
                        verbose_name="Yeniləmə Xatırlatma Günləri",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("expired", "Müddəti Keçib"),
                            ("pending_renewal", "Yeniləmə Gözləyir"),
                            ("suspended", "Dayandırılıb"),
                            ("revoked", "Ləğv Edilib"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_url",
                    models.URLField(
                        blank=True,
                        help_text="Sertifikatı yoxlamaq üçün link",
                        verbose_name="Yoxlama URL",
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="certifications/%Y/",
                        verbose_name="Sertifikat Faylı",
                    ),
                ),
                (
                    "requires_continuing_education",
                    models.BooleanField(
                        default=False, verbose_name="Davamlı Təhsil Tələb Edir"
                    ),
                ),
                (
                    "ce_hours_required",
                    models.IntegerField(
                        blank=True,
                        help_text="Yeniləmə üçün lazım olan davamlı təhsil saatları",
                        null=True,
                        verbose_name="Tələb olunan CE Saatları",
                    ),
                ),
                (
                    "ce_hours_completed",
                    models.IntegerField(
                        default=0, verbose_name="Tamamlanmış CE Saatları"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Xərc",
                    ),
                ),
                (
                    "company_sponsored",
                    models.BooleanField(
                        default=False,
                        verbose_name="Şirkət Tərəfindən Maliyyələşdirilir",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "is_required_for_role",
                    models.BooleanField(
                        default=False, verbose_name="Vəzifə üçün Məcburidir"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "related_competency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="certifications",
                        to="competencies.competency",
                        verbose_name="Əlaqəli Kompetensiya",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sertifikat",
                "verbose_name_plural": "Sertifikatlar",
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCertification",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "certification_name",
                    models.CharField(max_length=200, verbose_name="Sertifikat Adı"),
                ),
                (
                    "certification_code",
                    models.CharField(
                        blank=True,
                        help_text="Məsələn: PMP, AWS-SAA, CISSP",
                        max_length=100,
                        verbose_name="Sertifikat Kodu",
                    ),
                ),
                (
                    "issuing_organization",
                    models.CharField(
                        max_length=200, verbose_name="Təqdim Edən Təşkilat"
                    ),
                ),
                (
                    "credential_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Sertifikat ID"
                    ),
                ),
                ("issue_date", models.DateField(verbose_name="Verilmə Tarixi")),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitmə Tarixi"
                    ),
                ),
                (
                    "last_renewal_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Yeniləmə Tarixi"
                    ),
                ),
                (
                    "renewal_frequency",
                    models.CharField(
                        choices=[
                            ("annual", "İllik"),
                            ("biennial", "2 İllik"),
                            ("triennial", "3 İllik"),
                            ("lifetime", "Ömürlük"),
                            ("custom", "Xüsusi"),
                        ],
                        default="annual",
                        max_length=20,
                        verbose_name="Yeniləmə Tezliyi",
                    ),
                ),
                (
                    "renewal_reminder_days",
                    models.IntegerField(
                        default=60,
                        help_text="Bitmə tarixindən neçə gün əvvəl xatırlatma göndərsin",
                        verbose_name="Yeniləmə Xatırlatma Günləri",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("expired", "Müddəti Keçib"),
                            ("pending_renewal", "Yeniləmə Gözləyir"),
                            ("suspended", "Dayandırılıb"),
                            ("revoked", "Ləğv Edilib"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "verification_url",
                    models.URLField(
                        blank=True,
                        help_text="Sertifikatı yoxlamaq üçün link",
                        verbose_name="Yoxlama URL",
                    ),
                ),
                (
                    "certificate_file",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Sertifikat Faylı",
                    ),
                ),
                (
                    "requires_continuing_education",
                    models.BooleanField(
                        default=False, verbose_name="Davamlı Təhsil Tələb Edir"
                    ),
                ),
                (
                    "ce_hours_required",
                    models.IntegerField(
                        blank=True,
                        help_text="Yeniləmə üçün lazım olan davamlı təhsil saatları",
                        null=True,
                        verbose_name="Tələb olunan CE Saatları",
                    ),
                ),
                (
                    "ce_hours_completed",
                    models.IntegerField(
                        default=0, verbose_name="Tamamlanmış CE Saatları"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Xərc",
                    ),
                ),
                (
                    "company_sponsored",
                    models.BooleanField(
                        default=False,
                        verbose_name="Şirkət Tərəfindən Maliyyələşdirilir",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "is_required_for_role",
                    models.BooleanField(
                        default=False, verbose_name="Vəzifə üçün Məcburidir"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "related_competency",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="competencies.competency",
                        verbose_name="Əlaqəli Kompetensiya",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sertifikat",
                "verbose_name_plural": "historical Sertifikatlar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ContinuingEducationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_date", models.DateField(verbose_name="Fəaliyyət Tarixi")),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Saatlar"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        help_text="Məsələn: Vebinar, Konfrans, Kurs",
                        max_length=100,
                        verbose_name="Fəaliyyət Növü",
                    ),
                ),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "provider",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Təmin Edən"
                    ),
                ),
                (
                    "verification_document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ce_documents/%Y/",
                        verbose_name="Təsdiq Sənədi",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Təsdiqləndi"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ce_logs",
                        to="training.certification",
                        verbose_name="Sertifikat",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_ce_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
            ],
            options={
                "verbose_name": "Davamlı Təhsil Qeydi",
                "verbose_name_plural": "Davamlı Təhsil Qeydləri",
                "ordering": ["-activity_date"],
            },
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["user", "status"], name="training_ce_user_id_f5036f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(
                fields=["expiration_date"], name="training_ce_expirat_7cf2e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="certification",
            index=models.Index(fields=["status"], name="training_ce_status_ba94e8_idx"),
        ),
    ]
