# Generated by Django 5.1.4 on 2026-07-14 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_certification_historicalcertification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kateqoriya Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='training.coursecategory', verbose_name='Üst Kateqoriya')),
            ],
            options={
                'verbose_name': 'Kurs Kateqoriyası',
                'verbose_name_plural': 'Kurs Kateqoriyaları',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İmtahan Adı')),
                ('passing_score', models.IntegerField(default=50, verbose_name='Keçid Balı')),
                ('time_limit', models.IntegerField(blank=True, null=True, verbose_name='Müddət (Dəqiqə)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='training.trainingresource', verbose_name='Əlaqəli Kurs')),
            ],
            options={
                'verbose_name': 'İmtahan',
                'verbose_name_plural': 'İmtahanlar',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Öyrənmə Yolu Adı')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courses', models.ManyToManyField(related_name='learning_paths', to='training.trainingresource', verbose_name='Kurslar')),
            ],
            options={
                'verbose_name': 'Öyrənmə Yolu',
                'verbose_name_plural': 'Öyrənmə Yolları',
            },
        ),
    ]
