# Generated by Django 5.1.4 on 2026-07-14 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.SlugField(verbose_name='Kateqoriya')),
                ('key', models.CharField(max_length=100, verbose_name='Açar')),
                ('value', models.TextField(blank=True, verbose_name='Dəyər')),
                ('value_type', models.CharField(choices=[('text', 'Mətn'), ('int', 'Tam ədəd'), ('bool', 'Bəli/Xeyr'), ('json', 'JSON')], default='text', max_length=10, verbose_name='Dəyər tipi')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Təsvir')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Həssas dəyərlər UI-də maskalanır.', verbose_name='Həssas məlumat')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL, verbose_name='Yeniləyən')),
            ],
            options={
                'verbose_name': 'Sistem Parametri',
                'verbose_name_plural': 'Sistem Parametrləri',
                'ordering': ['category', 'key'],
                'unique_together': {('category', 'key')},
            },
        ),
    ]
