# Generated by Django 4.2.23 on 2025-10-10 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF Hesabat"),
                            ("excel", "Excel Hesabat"),
                            ("csv", "CSV Hesabat"),
                        ],
                        max_length=20,
                        verbose_name="Hesabat Növü",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("processing", "İşlənir"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Uğursuz"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="generated_reports/%Y/%m/",
                        verbose_name="Hesabat Faylı",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Task ID, parameterlər və s.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Xəta Mesajı"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarixi"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Tələb edən",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesabat Yaratma Loqu",
                "verbose_name_plural": "Hesabat Yaratma Loqları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "status"],
                        name="reports_rep_request_510537_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_rep_created_3cb1bc_idx"
                    ),
                ],
            },
        ),
    ]
