# Generated by Django 4.2.23 on 2025-10-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_add_report_generation_log"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="KPI snapshot tarixi",
                        unique=True,
                        verbose_name="Tarix",
                    ),
                ),
                (
                    "total_users",
                    models.IntegerField(default=0, verbose_name="Ümumi İstifadəçilər"),
                ),
                (
                    "active_users",
                    models.IntegerField(default=0, verbose_name="Aktiv İstifadəçilər"),
                ),
                (
                    "new_users_today",
                    models.IntegerField(
                        default=0, verbose_name="Bu gün qeydiyyatdan keçənlər"
                    ),
                ),
                (
                    "users_logged_in_today",
                    models.IntegerField(default=0, verbose_name="Bu gün giriş edənlər"),
                ),
                (
                    "total_campaigns",
                    models.IntegerField(default=0, verbose_name="Ümumi Kampaniyalar"),
                ),
                (
                    "active_campaigns",
                    models.IntegerField(default=0, verbose_name="Aktiv Kampaniyalar"),
                ),
                (
                    "total_evaluations",
                    models.IntegerField(
                        default=0, verbose_name="Ümumi Qiymətləndirmələr"
                    ),
                ),
                (
                    "completed_evaluations",
                    models.IntegerField(
                        default=0, verbose_name="Tamamlanmış Qiymətləndirmələr"
                    ),
                ),
                (
                    "evaluations_completed_today",
                    models.IntegerField(default=0, verbose_name="Bu gün tamamlananlar"),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Tamamlanma Faizi",
                    ),
                ),
                (
                    "total_departments",
                    models.IntegerField(default=0, verbose_name="Ümumi Şöbələr"),
                ),
                (
                    "total_trainings",
                    models.IntegerField(default=0, verbose_name="Ümumi Təlimlər"),
                ),
                (
                    "active_trainings",
                    models.IntegerField(default=0, verbose_name="Davam edən Təlimlər"),
                ),
                (
                    "login_attempts_today",
                    models.IntegerField(
                        default=0, verbose_name="Bu gün giriş cəhdləri"
                    ),
                ),
                (
                    "failed_login_attempts_today",
                    models.IntegerField(
                        default=0, verbose_name="Bu gün uğursuz girişlər"
                    ),
                ),
                (
                    "security_threats_detected",
                    models.IntegerField(
                        default=0, verbose_name="Aşkar edilmiş təhlükələr"
                    ),
                ),
                (
                    "average_response_time",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Millisaniyə ilə",
                        max_digits=8,
                        verbose_name="Orta cavab müddəti (ms)",
                    ),
                ),
                (
                    "database_size_mb",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Verilənlər bazası ölçüsü (MB)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sistem KPI",
                "verbose_name_plural": "Sistem KPI-ləri",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="reports_sys_date_1b58ea_idx")
                ],
            },
        ),
    ]
