# Generated by Django 4.2.23 on 2025-10-19 07:56

import apps.reports.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reports", "0003_systemkpi"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportBlueprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                (
                    "slug",
                    models.SlugField(max_length=210, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("evaluations", "Qiymətləndirmələr"),
                            ("training", "Təlim Resursları"),
                            ("compensation", "Kompensasiya"),
                            ("workforce", "İşçi Məlumatları"),
                        ],
                        default="evaluations",
                        max_length=50,
                        verbose_name="Məlumat Mənbəyi",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Seçilmiş sahələr, aqreqasiyalar və vizual komponentlər.",
                        verbose_name="Konfiqurasiya",
                    ),
                ),
                (
                    "default_filters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Defolt Filtrlər"
                    ),
                ),
                (
                    "columns",
                    models.JSONField(blank=True, default=list, verbose_name="Sütunlar"),
                ),
                (
                    "default_export_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="excel",
                        max_length=10,
                        verbose_name="Defolt Export Formatı",
                    ),
                ),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, verbose_name="Hamı üçün əlçatan"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivdir"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_blueprints",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesabat Şablonu",
                "verbose_name_plural": "Hesabat Şablonları",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="ReportSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Gündəlik"),
                            ("weekly", "Həftəlik"),
                            ("monthly", "Aylıq"),
                            ("once", "Bir dəfə"),
                        ],
                        default="weekly",
                        max_length=20,
                        verbose_name="Tezlik",
                    ),
                ),
                (
                    "interval",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Məsələn, 2 yazsanız hər 2 həftədən bir göndəriləcək.",
                        verbose_name="Interval (ədəd)",
                    ),
                ),
                (
                    "run_time",
                    models.TimeField(
                        default=apps.reports.models.default_schedule_time,
                        verbose_name="Göndərilmə Vaxtı",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Yalnız həftəlik planlamalar üçün tələb olunur.",
                        null=True,
                        verbose_name="Həftənin Günü (0=Bazar ertəsi)",
                    ),
                ),
                (
                    "day_of_month",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Aylıq planlamalar üçün 1-28 arası dəyər tövsiyə olunur.",
                        null=True,
                        verbose_name="Ayın Günü",
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("excel", "Excel"), ("csv", "CSV")],
                        default="excel",
                        max_length=10,
                        verbose_name="Export Formatı",
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Filtr və Parametrlər"
                    ),
                ),
                (
                    "additional_emails",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Əlavə E-poçtlar"
                    ),
                ),
                (
                    "send_email",
                    models.BooleanField(default=True, verbose_name="E-poçt Göndər"),
                ),
                (
                    "include_visualizations",
                    models.BooleanField(
                        default=True, verbose_name="Vizualizasiyaları daxil et"
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Növbəti İcra Tarixi"
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son İcra Tarixi"
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("processing", "İcra olunur"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Uğursuz"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Son Status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivdir"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="reports.reportblueprint",
                        verbose_name="Hesabat Şablonu",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True,
                        related_name="report_schedules",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qəbul edənlər",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesabat Planlaması",
                "verbose_name_plural": "Hesabat Planlamaları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportVisualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Sütun Diaqramı"),
                            ("line", "Xətt Diaqramı"),
                            ("pie", "Piroq Diaqramı"),
                            ("radar", "Radar Diaqramı"),
                            ("table", "Cədvəl"),
                        ],
                        default="table",
                        max_length=20,
                        verbose_name="Diaqram Tipi",
                    ),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Vizual Konfiqurasiya"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="Sıra")),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="Əsas Vizual"),
                ),
                (
                    "blueprint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visualizations",
                        to="reports.reportblueprint",
                        verbose_name="Hesabat Şablonu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hesabat Vizualı",
                "verbose_name_plural": "Hesabat Vizuaları",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReportScheduleLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Başlama Tarixi"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Tarixi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("processing", "İcra olunur"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Uğursuz"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="Mesaj")),
                (
                    "export_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_logs",
                        to="reports.reportgenerationlog",
                        verbose_name="Export Qeydi",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="reports.reportschedule",
                        verbose_name="Planlama",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planlama Loqu",
                "verbose_name_plural": "Planlama Loqları",
                "ordering": ["-triggered_at"],
            },
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["is_active", "next_run"], name="reports_rep_is_acti_75ce04_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportschedule",
            index=models.Index(
                fields=["frequency"], name="reports_rep_frequen_1e97ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reportblueprint",
            index=models.Index(
                fields=["data_source", "is_active"],
                name="reports_rep_data_so_8bed02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reportblueprint",
            index=models.Index(fields=["slug"], name="reports_rep_slug_5d8de1_idx"),
        ),
    ]
