# Generated by Django 5.1.4 on 2025-10-19 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_reportblueprint_reportschedule_reportvisualization_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduledReport",
            fields=[],
            options={
                "verbose_name": "Cədvəl Hesabatı",
                "verbose_name_plural": "Cədvəl Hesabatları",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("reports.reportschedule",),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="delivery_emails",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Əlavə E-poçtlar"
            ),
        ),
        migrations.CreateModel(
            name="CustomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ad")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Konfiqurasiya"
                    ),
                ),
                (
                    "query_definition",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Sorğu Tərifi"
                    ),
                ),
                (
                    "columns",
                    models.JSONField(blank=True, default=list, verbose_name="Sütunlar"),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=list, verbose_name="Filtrlər"),
                ),
                (
                    "visualization",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Vizualizasiyalar"
                    ),
                ),
                (
                    "last_run_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son İcra Vaxtı"
                    ),
                ),
                (
                    "last_run_summary",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Son İcra Xülasəsi"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivdir"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "blueprint",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custom_reports",
                        to="reports.reportblueprint",
                        verbose_name="Əsas Şablon",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Müəllif",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fərdi Hesabat",
                "verbose_name_plural": "Fərdi Hesabatlar",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="custom_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="schedules",
                to="reports.customreport",
                verbose_name="Fərdi Hesabat",
            ),
        ),
        migrations.AddIndex(
            model_name="customreport",
            index=models.Index(
                fields=["owner", "is_active"], name="reports_cus_owner_i_4effaa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="customreport",
            index=models.Index(
                fields=["created_at"], name="reports_cus_created_f1f469_idx"
            ),
        ),
    ]
