# Generated by Django 5.1.4 on 2025-10-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_scheduledreport_reportschedule_delivery_emails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportschedule",
            name="additional_emails",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Birbaşa E-poçt Ünvanları"
            ),
        ),
        migrations.AlterField(
            model_name="reportschedule",
            name="delivery_emails",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Birbaşa E-poçt Ünvanları"
            ),
        ),
    ]
