# Generated by Django 4.2.23 on 2025-10-09 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şöbə Adı")),
                ("code", models.CharField(max_length=20, verbose_name="Şöbə Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-poçt"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Yerləşmə"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
            ],
            options={
                "verbose_name": "Şöbə",
                "verbose_name_plural": "Şöbələr",
                "ordering": ["tree_id", "lft"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalDepartment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Şöbə Adı")),
                ("code", models.CharField(max_length=20, verbose_name="Şöbə Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-poçt"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Yerləşmə"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Şöbə",
                "verbose_name_plural": "historical Şöbələr",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalOrganization",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Təşkilat Adı"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Qısa Ad"),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=20, verbose_name="Təşkilat Kodu"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("address", models.TextField(blank=True, verbose_name="Ünvan")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-poçt"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Veb Sayt")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "established_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Təsis Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Təşkilat",
                "verbose_name_plural": "historical Təşkilatlar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPosition",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Vəzifə Adı")),
                ("code", models.CharField(max_length=20, verbose_name="Vəzifə Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="Vəzifə Öhdəlikləri"),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="1=Rəhbərlik, 2=Orta menecment, 3=Əməkdaş",
                        verbose_name="Səviyyə",
                    ),
                ),
                (
                    "required_education",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tələb Olunan Təhsil"
                    ),
                ),
                (
                    "required_experience",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tələb Olunan Təcrübə"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Vəzifə",
                "verbose_name_plural": "historical Vəzifələr",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Təşkilat Adı"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(blank=True, max_length=50, verbose_name="Qısa Ad"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Təşkilat Kodu"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("address", models.TextField(blank=True, verbose_name="Ünvan")),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Telefon"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-poçt"
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="Veb Sayt")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "established_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Təsis Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Təşkilat",
                "verbose_name_plural": "Təşkilatlar",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Vəzifə Adı")),
                ("code", models.CharField(max_length=20, verbose_name="Vəzifə Kodu")),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="Vəzifə Öhdəlikləri"),
                ),
                (
                    "level",
                    models.IntegerField(
                        default=1,
                        help_text="1=Rəhbərlik, 2=Orta menecment, 3=Əməkdaş",
                        verbose_name="Səviyyə",
                    ),
                ),
                (
                    "required_education",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tələb Olunan Təhsil"
                    ),
                ),
                (
                    "required_experience",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Tələb Olunan Təcrübə"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="departments.department",
                        verbose_name="Şöbə",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="departments.organization",
                        verbose_name="Təşkilat",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinate_positions",
                        to="departments.position",
                        verbose_name="Hesabat Verir",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vəzifə",
                "verbose_name_plural": "Vəzifələr",
                "ordering": ["level", "title"],
            },
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["code"], name="departments_code_7a7a1f_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active"], name="departments_is_acti_5ac9f2_idx"
            ),
        ),
        migrations.AddField(
            model_name="historicalposition",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="departments.department",
                verbose_name="Şöbə",
            ),
        ),
        migrations.AddField(
            model_name="historicalposition",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalposition",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="departments.organization",
                verbose_name="Təşkilat",
            ),
        ),
        migrations.AddField(
            model_name="historicalposition",
            name="reports_to",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="departments.position",
                verbose_name="Hesabat Verir",
            ),
        ),
        migrations.AddField(
            model_name="historicalorganization",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="head",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Şöbə Rəhbəri",
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="departments.organization",
                verbose_name="Təşkilat",
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="departments.department",
                verbose_name="Üst Şöbə",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Şöbə Rəhbəri",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="departments.organization",
                verbose_name="Təşkilat",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="departments.department",
                verbose_name="Üst Şöbə",
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["code"], name="departments_code_659216_idx"),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["level"], name="departments_level_dc8ed0_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="position",
            unique_together={("organization", "code")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="departments_code_35a421_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["is_active"], name="departments_is_acti_51d68f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tree_id", "lft"], name="departments_department_tref4ab"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "code")},
        ),
    ]
