# Generated by Django 5.1.4 on 2025-10-10 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="department",
            name="departments_department_tref4ab",
        ),
    ]
