# Generated by Django 5.1.4 on 2025-10-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0002_remove_department_departments_department_tref4ab"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalposition",
            name="level",
        ),
    ]
