# Generated by Django 5.1.4 on 2025-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0003_remove_historicalposition_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalposition",
            name="level",
            field=models.IntegerField(
                default=1,
                help_text="1=Rəhbərlik, 2=Orta menecment, 3=Əməkdaş",
                verbose_name="Səviyyə",
            ),
        ),
    ]
