# Generated by Django 4.2.23 on 2025-10-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0004_historicalposition_level"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["tree_id", "lft"], name="departments_department_tref4ab"
            ),
        ),
    ]
