# Generated by Django 5.1.4 on 2025-10-15 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0007_department_departments_department_tref4ab"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="department",
            name="departments_department_tref4ab",
        ),
    ]
