# Generated by Django 5.1.4 on 2025-10-11 07:46

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0004_historicalposition_level"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="Kompetensiya Adı"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Kompetensiya",
                "verbose_name_plural": "Kompetensiyalar",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="competencie_name_23d94b_idx"),
                    models.Index(
                        fields=["is_active"], name="competencie_is_acti_0b88da_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalCompetency",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="Kompetensiya Adı"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Kompetensiya",
                "verbose_name_plural": "historical Kompetensiyalar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ProficiencyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("basic", "Əsas"),
                            ("intermediate", "Orta"),
                            ("advanced", "Təkmil"),
                            ("expert", "Ekspert"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="Səviyyə Adı",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(max_length=100, verbose_name="Göstəriləcək Ad"),
                ),
                (
                    "score_min",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Minimum Bal",
                    ),
                ),
                (
                    "score_max",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Maksimum Bal",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bacarıq Səviyyəsi",
                "verbose_name_plural": "Bacarıq Səviyyələri",
                "ordering": ["score_min"],
                "indexes": [
                    models.Index(fields=["name"], name="competencie_name_43a725_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalUserSkill",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "current_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Qiymətləndirmədən əldə edilən son bal",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Cari Bal",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Təsdiqləndi"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("approved", "Təsdiqləndi"),
                            ("rejected", "Rədd Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Təsdiq Statusu",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "self_assessment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Özünüqiymətləndirmə Balı",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="competencies.competency",
                        verbose_name="Kompetensiya",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="competencies.proficiencylevel",
                        verbose_name="Səviyyə",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical İstifadəçi Bacarığı",
                "verbose_name_plural": "historical İstifadəçi Bacarıqları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPositionCompetency",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=50,
                        help_text="Bu kompetensiyanın vəzifə üçün əhəmiyyət dərəcəsi (1-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Çəki (%)",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Bu kompetensiya vəzifə üçün məcburidirmi?",
                        verbose_name="Məcburi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="competencies.competency",
                        verbose_name="Kompetensiya",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="departments.position",
                        verbose_name="Vəzifə",
                    ),
                ),
                (
                    "required_level",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="competencies.proficiencylevel",
                        verbose_name="Tələb Olunan Səviyyə",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Vəzifə Kompetensiyası",
                "verbose_name_plural": "historical Vəzifə Kompetensiyaları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="PositionCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=50,
                        help_text="Bu kompetensiyanın vəzifə üçün əhəmiyyət dərəcəsi (1-100%)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Çəki (%)",
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=True,
                        help_text="Bu kompetensiya vəzifə üçün məcburidirmi?",
                        verbose_name="Məcburi",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_competencies",
                        to="competencies.competency",
                        verbose_name="Kompetensiya",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="position_competencies",
                        to="departments.position",
                        verbose_name="Vəzifə",
                    ),
                ),
                (
                    "required_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position_requirements",
                        to="competencies.proficiencylevel",
                        verbose_name="Tələb Olunan Səviyyə",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vəzifə Kompetensiyası",
                "verbose_name_plural": "Vəzifə Kompetensiyaları",
                "ordering": ["-weight", "competency__name"],
                "indexes": [
                    models.Index(
                        fields=["position", "weight"],
                        name="competencie_positio_275513_idx",
                    ),
                    models.Index(
                        fields=["competency"], name="competencie_compete_b197dc_idx"
                    ),
                ],
                "unique_together": {("position", "competency")},
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Qiymətləndirmədən əldə edilən son bal",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Cari Bal",
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(default=False, verbose_name="Təsdiqləndi"),
                ),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("approved", "Təsdiqləndi"),
                            ("rejected", "Rədd Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Təsdiq Statusu",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "self_assessment_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Özünüqiymətləndirmə Balı",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_skills",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="competencies.competency",
                        verbose_name="Kompetensiya",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to="competencies.proficiencylevel",
                        verbose_name="Səviyyə",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_skills",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İstifadəçi Bacarığı",
                "verbose_name_plural": "İstifadəçi Bacarıqları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_approved"],
                        name="competencie_user_id_b83df4_idx",
                    ),
                    models.Index(
                        fields=["competency", "level"],
                        name="competencie_compete_ebce9f_idx",
                    ),
                    models.Index(
                        fields=["approval_status"],
                        name="competencie_approva_acd8f4_idx",
                    ),
                ],
                "unique_together": {("user", "competency")},
            },
        ),
    ]
