# Generated by Django 5.1.4 on 2025-10-11 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competencies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="competency",
            index=models.Index(
                fields=["name", "is_active"], name="competencie_name_eac81b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="proficiencylevel",
            index=models.Index(
                fields=["score_min", "score_max"], name="competencie_score_m_96389c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(
                fields=["user", "competency", "is_approved"],
                name="competencie_user_id_dc22be_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(
                fields=["current_score"], name="competencie_current_a60b10_idx"
            ),
        ),
    ]
