# Generated by Django 5.1.4 on 2026-07-14 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competencies', '0002_competency_competencie_name_eac81b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Davranış Təsviri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='competencies.competency', verbose_name='Kompetensiya')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviors', to='competencies.proficiencylevel', verbose_name='Səviyyə')),
            ],
            options={
                'verbose_name': 'Davranış İndikatoru',
                'verbose_name_plural': 'Davranış İndikatorları',
                'ordering': ['competency', 'level'],
            },
        ),
    ]
