# Generated by Django 5.1.4 on 2025-10-10 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("description", models.TextField(verbose_name="Təsvir")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Açıq"),
                            ("in_progress", "İcrada"),
                            ("resolved", "Həll Edildi"),
                            ("closed", "Bağlandı"),
                        ],
                        default="open",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Aşağı"),
                            ("medium", "Orta"),
                            ("high", "Yüksək"),
                            ("urgent", "Təcili"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Prioritet",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Həll Tarixi"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təyin Edildi",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dəstək Sorğusu",
                "verbose_name_plural": "Dəstək Sorğuları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Şərh")),
                (
                    "is_internal",
                    models.BooleanField(
                        default=False,
                        help_text="Yalnız support komandası üçün görünən",
                        verbose_name="Daxili Qeyd",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="support.supportticket",
                        verbose_name="Sorğu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sorğu Şərhi",
                "verbose_name_plural": "Sorğu Şərhləri",
                "ordering": ["created_at"],
            },
        ),
    ]
