# Generated by Django 5.1.4 on 2026-07-14 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='SLA Siyasəti')),
                ('priority', models.CharField(choices=[('low', 'Aşağı'), ('medium', 'Orta'), ('high', 'Yüksək'), ('critical', 'Kritik')], max_length=20)),
                ('response_time_hours', models.IntegerField(verbose_name='Cavablandırma Müddəti (saat)')),
                ('resolution_time_hours', models.IntegerField(verbose_name='Həll Müddəti (saat)')),
            ],
            options={
                'verbose_name': 'SLA Siyasəti',
                'verbose_name_plural': 'SLA Siyasətləri',
            },
        ),
        migrations.CreateModel(
            name='TicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kateqoriya Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'Bilet Kateqoriyası',
                'verbose_name_plural': 'Bilet Kateqoriyaları',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Məqalə Başlığı')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('views_count', models.IntegerField(default=0, verbose_name='Baxış Sayı')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.ticketcategory')),
            ],
            options={
                'verbose_name': 'Bilik Məqaləsi',
                'verbose_name_plural': 'Bilik Məqalələri',
            },
        ),
    ]
