# Generated by Django 5.1.4 on 2026-07-13 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_flags', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureflag',
            options={'verbose_name': 'Xüsusiyyət Bayrağı', 'verbose_name_plural': 'Xüsusiyyət Bayraqları'},
        ),
        migrations.AlterModelOptions(
            name='featureflagrule',
            options={'verbose_name': 'Bayraq Qaydası', 'verbose_name_plural': 'Bayraq Qaydaları'},
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktivdir'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='name',
            field=models.CharField(help_text='Xüsusiyyət bayrağı üçün unikal kod adı, məsələn: AI_SCREENING', max_length=100, unique=True, verbose_name='Bayraq adı'),
        ),
        migrations.AlterField(
            model_name='featureflag',
            name='percentage_rollout',
            field=models.PositiveSmallIntegerField(default=100, help_text='İstifadəçilərin neçə faizinə tətbiq olunacaq (0-100)', verbose_name='Yayılma faizi'),
        ),
        migrations.AlterField(
            model_name='featureflagrule',
            name='flag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='feature_flags.featureflag', verbose_name='Bayraq'),
        ),
        migrations.AlterField(
            model_name='featureflagrule',
            name='target_departments',
            field=models.JSONField(blank=True, default=list, help_text='Departament ID-lərinin siyahısı. Məsələn: [3, 7]', null=True, verbose_name='Hədəf departamentlər'),
        ),
        migrations.AlterField(
            model_name='featureflagrule',
            name='target_users',
            field=models.JSONField(blank=True, default=list, help_text='Bu bayrağın xüsusi olaraq aktiv olacağı İstifadəçi ID-lərinin siyahısı. Məsələn: [1, 2, 5]', null=True, verbose_name='Hədəf istifadəçilər'),
        ),
    ]
