# Generated by Django 5.1.4 on 2026-07-13 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('workflow_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowcondition',
            options={'verbose_name': 'İş Axını Şərti', 'verbose_name_plural': 'İş Axını Şərtləri'},
        ),
        migrations.AlterModelOptions(
            name='workflowhistory',
            options={'verbose_name': 'İş Axını Tarixi', 'verbose_name_plural': 'İş Axını Tarixçəsi'},
        ),
        migrations.AlterModelOptions(
            name='workflowinstance',
            options={'verbose_name': 'İş Axını İnstansiyası', 'verbose_name_plural': 'İş Axını İnstansiyaları'},
        ),
        migrations.AlterModelOptions(
            name='workflowinstancestep',
            options={'verbose_name': 'İnstansiya Addımı', 'verbose_name_plural': 'İnstansiya Addımları'},
        ),
        migrations.AlterModelOptions(
            name='workflowstep',
            options={'ordering': ['step_order'], 'verbose_name': 'İş Axını Addımı', 'verbose_name_plural': 'İş Axını Addımları'},
        ),
        migrations.AlterModelOptions(
            name='workflowtemplate',
            options={'verbose_name': 'İş Axını Şablonu', 'verbose_name_plural': 'İş Axını Şablonları'},
        ),
        migrations.AlterModelOptions(
            name='workflowtransition',
            options={'verbose_name': 'İş Axını Keçidi', 'verbose_name_plural': 'İş Axını Keçidləri'},
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Şərt adı'),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='rule_json',
            field=models.JSONField(blank=True, default=dict, help_text='Şərt qaydalarını JSON formatında daxil edin. Məsələn: {"==": [{"var": "department"}, "IT"]}', verbose_name='Şərt qaydaları (JSON)'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='action',
            field=models.CharField(max_length=100, verbose_name='Əməliyyat'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İcraçı'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Şərhlər'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='workflow_engine.workflowinstance', verbose_name='İnstansiya'),
        ),
        migrations.AlterField(
            model_name='workflowhistory',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_engine.workflowstep', verbose_name='Addım'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Məzmun tipi'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Obyekt ID'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_workflows', to=settings.AUTH_USER_MODEL, verbose_name='Müraciət edən'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Gözləyir'), ('IN_PROGRESS', 'Davam edir'), ('COMPLETED', 'Tamamlandı'), ('REJECTED', 'Rədd edildi'), ('CANCELLED', 'Ləğv edildi')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workflowinstance',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='workflow_engine.workflowtemplate', verbose_name='Şablon'),
        ),
        migrations.AlterField(
            model_name='workflowinstancestep',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Təyin olunan'),
        ),
        migrations.AlterField(
            model_name='workflowinstancestep',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_steps', to='workflow_engine.workflowinstance', verbose_name='İnstansiya'),
        ),
        migrations.AlterField(
            model_name='workflowinstancestep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Gözləyir'), ('APPROVED', 'Təsdiqləndi'), ('REJECTED', 'Rədd edildi'), ('SKIPPED', 'Keçildi')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='workflowinstancestep',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow_engine.workflowstep', verbose_name='Addım'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Addımın adı'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_order',
            field=models.PositiveIntegerField(verbose_name='Sıra nömrəsi'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('APPROVAL', 'Təsdiq'), ('AUTOMATIC_TASK', 'Avtomatik tapşırıq'), ('NOTIFICATION', 'Bildiriş'), ('CONDITION', 'Şərt yoxlama')], default='APPROVAL', max_length=50, verbose_name='Addım növü'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow_engine.workflowtemplate', verbose_name='Şablon'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivdir'),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Şablon adı'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_engine.workflowcondition', verbose_name='Şərt'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='destination_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflow_engine.workflowstep', verbose_name='Hədəf addımı'),
        ),
        migrations.AlterField(
            model_name='workflowtransition',
            name='source_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflow_engine.workflowstep', verbose_name='Çıxış addımı'),
        ),
    ]
