# Generated by Django 5.1.4 on 2026-07-14 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_engine', '0002_alter_workflowcondition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('INFO', 'Məlumat'), ('WARNING', 'Xəbərdarlıq'), ('ERROR', 'Xəta')], max_length=20, verbose_name='Səviyyə')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detallar')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow_engine.workflowinstance', verbose_name='İnstansiya')),
            ],
            options={
                'verbose_name': 'İş Axını Loqu',
                'verbose_name_plural': 'İş Axını Loqları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.CharField(max_length=20, verbose_name='Versiya Nömrəsi')),
                ('schema_data', models.JSONField(default=dict, verbose_name='Sxem (JSON)')),
                ('is_published', models.BooleanField(default=False, verbose_name='Dərc edilib')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaradıcı')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflow_engine.workflowtemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'İş Axını Versiyası',
                'verbose_name_plural': 'İş Axını Versiyaları',
                'ordering': ['-created_at'],
            },
        ),
    ]
