# Generated by Django 5.1.4 on 2026-07-13 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abacpolicy',
            options={'verbose_name': 'ABAC Siyasəti', 'verbose_name_plural': 'ABAC Siyasətləri'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'verbose_name': 'İcazə', 'verbose_name_plural': 'İcazələr'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Rollar'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'verbose_name': 'Rol İcazəsi', 'verbose_name_plural': 'Rol İcazələri'},
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': 'İstifadəçi Rolu', 'verbose_name_plural': 'İstifadəçi Rolları'},
        ),
        migrations.AlterField(
            model_name='abacpolicy',
            name='action',
            field=models.CharField(help_text='Əməliyyat növü, məsələn: approve, read, update', max_length=100, verbose_name='Əməliyyat'),
        ),
        migrations.AlterField(
            model_name='abacpolicy',
            name='condition_json',
            field=models.JSONField(blank=True, default=dict, help_text='JSONLogic formatında şərt qaydalarını daxil edin. Məsələn: {"==": [{"var": "department"}, "IT"]}', verbose_name='Şərt qaydaları (JSON)'),
        ),
        migrations.AlterField(
            model_name='abacpolicy',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='abacpolicy',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Siyasət adı'),
        ),
        migrations.AlterField(
            model_name='abacpolicy',
            name='resource',
            field=models.CharField(help_text='Siyasətin tətbiq olunduğu resurs, məsələn: LeaveRequest', max_length=255, verbose_name='Resurs'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='code',
            field=models.CharField(help_text='Məsələn: workflow:create, leave:approve', max_length=255, unique=True, verbose_name='İcazə kodu'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(help_text='İcazənin aid olduğu modul adı', max_length=100, verbose_name='Modul'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_system',
            field=models.BooleanField(default=False, verbose_name='Sistem roludur'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Rol adı'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.permission', verbose_name='İcazə'),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='access_control.role', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.role', verbose_name='Rol'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi'),
        ),
    ]
