# Generated by Django 5.1.4 on 2026-07-14 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_abacpolicy_options_alter_permission_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100, verbose_name='Əməliyyat')),
                ('resource', models.CharField(max_length=255, verbose_name='Resurs')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Ünvanı')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('status', models.CharField(default='SUCCESS', max_length=50, verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_history', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Giriş Tarixçəsi',
                'verbose_name_plural': 'Giriş Tarixçələri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(verbose_name='Səbəb')),
                ('status', models.CharField(choices=[('PENDING', 'Gözləyir'), ('APPROVED', 'Təsdiqləndi'), ('REJECTED', 'Rədd edildi')], default='PENDING', max_length=20, verbose_name='Status')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='access_requests_approved', to=settings.AUTH_USER_MODEL, verbose_name='Təsdiqləyən')),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.permission', verbose_name='Tələb olunan İcazə')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_requests_sent', to=settings.AUTH_USER_MODEL, verbose_name='Müraciət edən')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.role', verbose_name='Tələb olunan Rol')),
            ],
            options={
                'verbose_name': 'Giriş İcazəsi Müraciəti',
                'verbose_name_plural': 'Giriş İcazəsi Müraciətləri',
            },
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Qrup adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıqlama')),
                ('roles', models.ManyToManyField(blank=True, related_name='groups', to='access_control.role', verbose_name='Rollar')),
                ('users', models.ManyToManyField(blank=True, related_name='access_groups', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçilər')),
            ],
            options={
                'verbose_name': 'İstifadəçi Qrupu',
                'verbose_name_plural': 'İstifadəçi Qrupları',
            },
        ),
    ]
