# Generated by Django 5.1.4 on 2026-07-14 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce_planning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_retirement_date', models.DateField(verbose_name='Gözlənilən Təqaüd Tarixi')),
                ('risk_level', models.CharField(choices=[('low', 'Aşağı'), ('medium', 'Orta'), ('high', 'Yüksək'), ('critical', 'Kritik')], default='low', max_length=20, verbose_name='Risq Səviyyəsi')),
                ('succession_plan_ready', models.BooleanField(default=False, verbose_name='Varislik Planı Hazırdır')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retirement_forecast', to=settings.AUTH_USER_MODEL, verbose_name='İşçi')),
            ],
            options={
                'verbose_name': 'Təqaüd Proqnozu',
                'verbose_name_plural': 'Təqaüd Proqnozları',
                'ordering': ['expected_retirement_date'],
            },
        ),
    ]
