# Generated by Django 4.2.23 on 2025-10-16 07:32

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Ad"),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Kod"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "days_per_year",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                        verbose_name="İllik Gün Sayı",
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum Ardıcıl Gün Sayı"
                    ),
                ),
                ("is_paid", models.BooleanField(default=True, verbose_name="Ödənişli")),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True, verbose_name="Təsdiq Tələb Olunur"
                    ),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False, verbose_name="Sənəd Tələb Olunur"
                    ),
                ),
                (
                    "carry_forward",
                    models.BooleanField(
                        default=False, verbose_name="Növbəti İlə Keçir"
                    ),
                ),
                (
                    "max_carry_forward_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum Keçid Gün Sayı"
                    ),
                ),
                (
                    "notice_days",
                    models.IntegerField(default=3, verbose_name="Bildiriş Günləri"),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Rəng Kodu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Məzuniyyət Növü",
                "verbose_name_plural": "Məzuniyyət Növləri",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlanğıc Tarixi")),
                ("end_date", models.DateField(verbose_name="Bitmə Tarixi")),
                (
                    "number_of_days",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Gün Sayı"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Səbəb")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("pending", "Gözləyir"),
                            ("approved", "Təsdiqləndi"),
                            ("rejected", "Rədd Edildi"),
                            ("cancelled", "Ləğv Edildi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="leave_attachments/%Y/%m/",
                        verbose_name="Əlavə Sənəd",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rədd Səbəbi"),
                ),
                (
                    "is_half_day_start",
                    models.BooleanField(
                        default=False, verbose_name="Başlanğıc Yarım Gün"
                    ),
                ),
                (
                    "is_half_day_end",
                    models.BooleanField(default=False, verbose_name="Bitmə Yarım Gün"),
                ),
                (
                    "emergency",
                    models.BooleanField(default=False, verbose_name="Təcili"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="leave_attendance.leavetype",
                        verbose_name="Məzuniyyət Növü",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Məzuniyyət Sorğusu",
                "verbose_name_plural": "Məzuniyyət Sorğuları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(verbose_name="İl")),
                (
                    "entitled_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Hüquqlu Gün Sayı",
                    ),
                ),
                (
                    "used_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="İstifadə Olunan Gün Sayı",
                    ),
                ),
                (
                    "pending_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Gözləyən Gün Sayı",
                    ),
                ),
                (
                    "carried_forward_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Keçmiş Gün Sayı",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="leave_attendance.leavetype",
                        verbose_name="Məzuniyyət Növü",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Məzuniyyət Qalığı",
                "verbose_name_plural": "Məzuniyyət Qalıqları",
                "ordering": ["-year", "user", "leave_type"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ad")),
                ("date", models.DateField(verbose_name="Tarix")),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public", "Dövlət Bayramı"),
                            ("religious", "Dini Bayram"),
                            ("company", "Şirkət Bayramı"),
                            ("other", "Digər"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Bayram Növü",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Təkrarlanan"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bayram",
                "verbose_name_plural": "Bayramlar",
                "ordering": ["date"],
                "indexes": [
                    models.Index(fields=["date"], name="leave_atten_date_282b20_idx"),
                    models.Index(
                        fields=["is_active"], name="leave_atten_is_acti_a31c49_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalLeaveType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(db_index=True, max_length=100, verbose_name="Ad"),
                ),
                (
                    "code",
                    models.CharField(db_index=True, max_length=20, verbose_name="Kod"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                (
                    "days_per_year",
                    models.DecimalField(
                        decimal_places=1,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0"))
                        ],
                        verbose_name="İllik Gün Sayı",
                    ),
                ),
                (
                    "max_consecutive_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum Ardıcıl Gün Sayı"
                    ),
                ),
                ("is_paid", models.BooleanField(default=True, verbose_name="Ödənişli")),
                (
                    "requires_approval",
                    models.BooleanField(
                        default=True, verbose_name="Təsdiq Tələb Olunur"
                    ),
                ),
                (
                    "requires_document",
                    models.BooleanField(
                        default=False, verbose_name="Sənəd Tələb Olunur"
                    ),
                ),
                (
                    "carry_forward",
                    models.BooleanField(
                        default=False, verbose_name="Növbəti İlə Keçir"
                    ),
                ),
                (
                    "max_carry_forward_days",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Maksimum Keçid Gün Sayı"
                    ),
                ),
                (
                    "notice_days",
                    models.IntegerField(default=3, verbose_name="Bildiriş Günləri"),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#3B82F6", max_length=7, verbose_name="Rəng Kodu"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Məzuniyyət Növü",
                "verbose_name_plural": "historical Məzuniyyət Növləri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLeaveRequest",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlanğıc Tarixi")),
                ("end_date", models.DateField(verbose_name="Bitmə Tarixi")),
                (
                    "number_of_days",
                    models.DecimalField(
                        decimal_places=1, max_digits=5, verbose_name="Gün Sayı"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Səbəb")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("pending", "Gözləyir"),
                            ("approved", "Təsdiqləndi"),
                            ("rejected", "Rədd Edildi"),
                            ("cancelled", "Ləğv Edildi"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "attachment",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Əlavə Sənəd",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="Rədd Səbəbi"),
                ),
                (
                    "is_half_day_start",
                    models.BooleanField(
                        default=False, verbose_name="Başlanğıc Yarım Gün"
                    ),
                ),
                (
                    "is_half_day_end",
                    models.BooleanField(default=False, verbose_name="Bitmə Yarım Gün"),
                ),
                (
                    "emergency",
                    models.BooleanField(default=False, verbose_name="Təcili"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leave_attendance.leavetype",
                        verbose_name="Məzuniyyət Növü",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Məzuniyyət Sorğusu",
                "verbose_name_plural": "historical Məzuniyyət Sorğuları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLeaveBalance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="İl")),
                (
                    "entitled_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Hüquqlu Gün Sayı",
                    ),
                ),
                (
                    "used_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="İstifadə Olunan Gün Sayı",
                    ),
                ),
                (
                    "pending_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Gözləyən Gün Sayı",
                    ),
                ),
                (
                    "carried_forward_days",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("0.0"),
                        max_digits=5,
                        verbose_name="Keçmiş Gün Sayı",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leave_attendance.leavetype",
                        verbose_name="Məzuniyyət Növü",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Məzuniyyət Qalığı",
                "verbose_name_plural": "historical Məzuniyyət Qalıqları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalHoliday",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Ad")),
                ("date", models.DateField(verbose_name="Tarix")),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("public", "Dövlət Bayramı"),
                            ("religious", "Dini Bayram"),
                            ("company", "Şirkət Bayramı"),
                            ("other", "Digər"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="Bayram Növü",
                    ),
                ),
                (
                    "is_recurring",
                    models.BooleanField(default=False, verbose_name="Təkrarlanan"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Bayram",
                "verbose_name_plural": "historical Bayramlar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAttendance",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarix")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "İştirak Edib"),
                            ("absent", "İştirak Etməyib"),
                            ("half_day", "Yarım Gün"),
                            ("late", "Gecikmə"),
                            ("on_leave", "Məzuniyyətdə"),
                            ("holiday", "Bayram"),
                            ("weekend", "Həftə Sonu"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "check_in",
                    models.TimeField(blank=True, null=True, verbose_name="Giriş Vaxtı"),
                ),
                (
                    "check_out",
                    models.TimeField(blank=True, null=True, verbose_name="Çıxış Vaxtı"),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="İş Saatı",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="Gecikməsi (Dəqiqə)"),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(default=0, verbose_name="Erkən Çıxış (Dəqiqə)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="leave_attendance.leaverequest",
                        verbose_name="Məzuniyyət Sorğusu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical İştirak Qeydi",
                "verbose_name_plural": "historical İştirak Qeydləri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Tarix")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "İştirak Edib"),
                            ("absent", "İştirak Etməyib"),
                            ("half_day", "Yarım Gün"),
                            ("late", "Gecikmə"),
                            ("on_leave", "Məzuniyyətdə"),
                            ("holiday", "Bayram"),
                            ("weekend", "Həftə Sonu"),
                        ],
                        default="present",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "check_in",
                    models.TimeField(blank=True, null=True, verbose_name="Giriş Vaxtı"),
                ),
                (
                    "check_out",
                    models.TimeField(blank=True, null=True, verbose_name="Çıxış Vaxtı"),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="İş Saatı",
                    ),
                ),
                (
                    "late_minutes",
                    models.IntegerField(default=0, verbose_name="Gecikməsi (Dəqiqə)"),
                ),
                (
                    "early_leave_minutes",
                    models.IntegerField(default=0, verbose_name="Erkən Çıxış (Dəqiqə)"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "leave_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="attendance_records",
                        to="leave_attendance.leaverequest",
                        verbose_name="Məzuniyyət Sorğusu",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_attendance",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
            ],
            options={
                "verbose_name": "İştirak Qeydi",
                "verbose_name_plural": "İştirak Qeydləri",
                "ordering": ["-date", "user"],
            },
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["user", "status"], name="leave_atten_user_id_dd947d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(
                fields=["start_date", "end_date"], name="leave_atten_start_d_cc6953_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaverequest",
            index=models.Index(fields=["status"], name="leave_atten_status_26f77b_idx"),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(
                fields=["user", "year"], name="leave_atten_user_id_23dbb5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leavebalance",
            index=models.Index(
                fields=["leave_type", "year"], name="leave_atten_leave_t_24ef17_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("user", "leave_type", "year")},
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["user", "date"], name="leave_atten_user_id_5ca70b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["date", "status"], name="leave_atten_date_b017ba_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("user", "date")},
        ),
    ]
