# Generated by Django 5.1.4 on 2026-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year_start_month', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], default=1, verbose_name='Maliyyə İlinin Başlanğıc Ayı')),
                ('default_work_start_time', models.TimeField(default='09:00:00', verbose_name='Standart İş Başlama Vaxtı')),
                ('default_work_end_time', models.TimeField(default='18:00:00', verbose_name='Standart İş Bitmə Vaxtı')),
                ('working_days_per_week', models.IntegerField(default=5, verbose_name='Həftəlik İş Günləri')),
                ('allow_negative_balance', models.BooleanField(default=False, verbose_name='Mənfi Qalığa İcazə Ver')),
                ('max_negative_balance', models.IntegerField(default=0, verbose_name='Maksimum Mənfi Qalıq')),
            ],
            options={
                'verbose_name': 'Məzuniyyət Tənzimləməsi',
                'verbose_name_plural': 'Məzuniyyət Tənzimləmələri',
            },
        ),
    ]
