# Generated by Django 5.1.4 on 2026-07-13 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_engine', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalchain',
            options={'verbose_name': 'Təsdiq Zənciri', 'verbose_name_plural': 'Təsdiq Zəncirləri'},
        ),
        migrations.AlterModelOptions(
            name='approvaldelegation',
            options={'verbose_name': 'Təsdiq Delegasiyası', 'verbose_name_plural': 'Təsdiq Delegasiyaları'},
        ),
        migrations.AlterModelOptions(
            name='approvallog',
            options={'verbose_name': 'Təsdiq Jurnalı', 'verbose_name_plural': 'Təsdiq Jurnalları'},
        ),
        migrations.AlterModelOptions(
            name='approvalnode',
            options={'ordering': ['order'], 'verbose_name': 'Təsdiq Qovşağı', 'verbose_name_plural': 'Təsdiq Qovşaqları'},
        ),
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'verbose_name': 'Təsdiq Müraciəti', 'verbose_name_plural': 'Təsdiq Müraciətləri'},
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='description',
            field=models.TextField(blank=True, verbose_name='Açıqlama'),
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivdir'),
        ),
        migrations.AlterField(
            model_name='approvalchain',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Zəncir adı'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='delegatee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='Səlahiyyət alan'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='Səlahiyyət verən'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='end_date',
            field=models.DateTimeField(verbose_name='Bitmə tarixi'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivdir'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='start_date',
            field=models.DateTimeField(verbose_name='Başlanğıc tarixi'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='action',
            field=models.CharField(max_length=50, verbose_name='Əməliyyat'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İcraçı'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='comments',
            field=models.TextField(blank=True, verbose_name='Şərhlər'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval_engine.approvalnode', verbose_name='Qovşaq'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='approval_engine.approvalrequest', verbose_name='Müraciət'),
        ),
        migrations.AlterField(
            model_name='approvalnode',
            name='approver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Təsdiq edən istifadəçi'),
        ),
        migrations.AlterField(
            model_name='approvalnode',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='approval_engine.approvalchain', verbose_name='Zəncir'),
        ),
        migrations.AlterField(
            model_name='approvalnode',
            name='node_type',
            field=models.CharField(choices=[('USER', 'Konkret İstifadəçi'), ('ROLE', 'Konkret Rol'), ('MANAGER', 'Birbaşa Rəhbər'), ('DYNAMIC', 'Dinamik Şərt')], max_length=50, verbose_name='Qovşaq növü'),
        ),
        migrations.AlterField(
            model_name='approvalnode',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Sıra nömrəsi'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='approval_engine.approvalchain', verbose_name='Zəncir'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Məzmun tipi'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='current_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='approval_engine.approvalnode', verbose_name='Cari qovşaq'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='Obyekt ID'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to=settings.AUTH_USER_MODEL, verbose_name='Müraciət edən'),
        ),
        migrations.AlterField(
            model_name='approvalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Gözləyir'), ('APPROVED', 'Təsdiqləndi'), ('REJECTED', 'Rədd edildi')], default='PENDING', max_length=50, verbose_name='Status'),
        ),
    ]
