# Generated by Django 5.1.4 on 2026-07-14 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval_engine', '0002_alter_approvalchain_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Qayda adı')),
                ('condition_json', models.JSONField(blank=True, default=dict, verbose_name='Şərtlər (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='approval_engine.approvalchain', verbose_name='Zəncir')),
            ],
            options={
                'verbose_name': 'Təsdiq Qaydası',
                'verbose_name_plural': 'Təsdiq Qaydaları',
            },
        ),
    ]
