# Generated by Django 4.2.23 on 2025-10-09 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("development_plans", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentgoal",
            name="approval_note",
            field=models.TextField(blank=True, verbose_name="Təsdiq Qeydi"),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_goals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="developmentgoal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Qaralama"),
                    ("pending_approval", "Təsdiq Gözləyir"),
                    ("active", "Aktiv"),
                    ("completed", "Tamamlanmış"),
                    ("cancelled", "Ləğv Edilmiş"),
                    ("rejected", "Rədd Edilmiş"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
