# Generated by Django 4.2.23 on 2025-10-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_plans", "0002_developmentgoal_approval_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresslog",
            name="is_draft",
            field=models.BooleanField(default=False, verbose_name="Layihə"),
        ),
        migrations.AddField(
            model_name="progresslog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
