# Generated by Django 4.2.23 on 2025-10-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("development_plans", "0003_progresslog_is_draft_progresslog_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentgoal",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="Təsdiqlənib"),
        ),
    ]
