# Generated by Django 4.2.23 on 2025-10-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("development_plans", "0004_developmentgoal_is_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developmentgoal",
            name="is_approved",
        ),
    ]
