# Generated by Django 4.2.23 on 2025-10-21 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0013_department_departments_department_tref4ab"),
        (
            "development_plans",
            "0007_historicalmilestone_historicalobjectiveupdate_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="developmentgoal",
            name="alignment_percentage",
            field=models.IntegerField(
                default=100,
                help_text="Bu məqsədin valideyn məqsədə uyğunluq dərəcəsi (0-100)",
                verbose_name="Uyğunluq Faizi",
            ),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="goal_level",
            field=models.CharField(
                choices=[
                    ("organizational", "Təşkilati"),
                    ("departmental", "Departament"),
                    ("team", "Komanda"),
                    ("individual", "Fərdi"),
                ],
                default="individual",
                help_text="Bu məqsədin təşkilati iyerarxiyada yerləşdiyi səviyyə",
                max_length=20,
                verbose_name="Məqsəd Səviyyəsi",
            ),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="parent_goal",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu məqsədin əsaslandığı daha yüksək səviyyəli məqsəd",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_goals",
                to="development_plans.developmentgoal",
                verbose_name="Valideyn Məqsəd",
            ),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="progress_percentage",
            field=models.IntegerField(
                default=0,
                help_text="Məqsədə nail olma faizi (0-100)",
                verbose_name="İrəliləyiş Faizi",
            ),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="related_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="department_goals",
                to="departments.department",
                verbose_name="Əlaqəli Departament",
            ),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="strategic_objective",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aligned_goals",
                to="development_plans.strategicobjective",
                verbose_name="Strateji Məqsəd",
            ),
        ),
        migrations.AddField(
            model_name="developmentgoal",
            name="weight_in_parent",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bu məqsədin valideyn məqsədin nail olunmasındakı payı (%)",
                max_digits=5,
                verbose_name="Valideyn Məqsəddə Çəki",
            ),
        ),
    ]
