# Generated by Django 5.1.4 on 2026-07-14 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_jobtitle_historicaljobtitle'),
        ('development_plans', '0008_developmentgoal_alignment_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Başlanğıc Tarixi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitmə Tarixi')),
                ('status', models.CharField(choices=[('not_started', 'Başlamayıb'), ('in_progress', 'Davam edir'), ('completed', 'Tamamlandı'), ('cancelled', 'Ləğv edildi')], default='not_started', max_length=20, verbose_name='Status')),
                ('key_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='development_plans.keyresult')),
                ('objective', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='development_plans.strategicobjective')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Təşəbbüs',
                'verbose_name_plural': 'Təşəbbüslər',
            },
        ),
        migrations.CreateModel(
            name='OKRTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Şablon Adı')),
                ('objective_title', models.CharField(max_length=255, verbose_name='Məqsəd Adı')),
                ('objective_description', models.TextField(blank=True, verbose_name='Məqsəd Təsviri')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='departments.department')),
            ],
            options={
                'verbose_name': 'OKR Şablonu',
                'verbose_name_plural': 'OKR Şablonları',
            },
        ),
    ]
