# Generated by Django 5.1.4 on 2025-10-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("onboarding", "0002_default_template"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="marketsalarybenchmark",
            new_name="onboarding__title_f6c2b0_idx",
            old_name="onboarding_title_r_1e763a_idx",
        ),
        migrations.RenameIndex(
            model_name="marketsalarybenchmark",
            new_name="onboarding__departm_495fe7_idx",
            old_name="onboarding_departme_640cb4_idx",
        ),
        migrations.RenameIndex(
            model_name="marketsalarybenchmark",
            new_name="onboarding__effecti_cdfd68_idx",
            old_name="onboarding_effecti_5f7ea8_idx",
        ),
        migrations.RenameIndex(
            model_name="onboardingprocess",
            new_name="onboarding__status_185b86_idx",
            old_name="onboarding_status_08f1f6_idx",
        ),
        migrations.RenameIndex(
            model_name="onboardingprocess",
            new_name="onboarding__employe_ca0d24_idx",
            old_name="onboarding_employee__5a9042_idx",
        ),
        migrations.RenameIndex(
            model_name="onboardingtask",
            new_name="onboarding__status_0eb39f_idx",
            old_name="onboarding_status_af082f_idx",
        ),
        migrations.RenameIndex(
            model_name="onboardingtask",
            new_name="onboarding__task_ty_bbb98d_idx",
            old_name="onboarding_task_typ_d111cc_idx",
        ),
        migrations.RenameIndex(
            model_name="onboardingtask",
            new_name="onboarding__due_dat_2e3cc3_idx",
            old_name="onboarding_due_date_2ffdf8_idx",
        ),
    ]
