# Generated by Django 5.1.4 on 2025-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "onboarding",
            "0003_rename_onboarding_title_r_1e763a_idx_onboarding__title_f6c2b0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("general", "Ümumi Tapşırıq"),
                    ("performance_review", "Performans Qiymətləndirmə Başlat"),
                    ("salary_recommendation", "Maaş Artımı Tövsiyəsi"),
                    ("training_plan", "Təlim Planı Yarat"),
                ],
                default="general",
                max_length=40,
                verbose_name="Tapşırıq Tipi",
            ),
        ),
    ]
