# Generated by Django 5.1.4 on 2026-07-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_alter_onboardingtask_task_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onboardingprocess',
            unique_together=set(),
        ),
    ]
