# Generated by Django 5.1.4 on 2026-07-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_onboardingprocess_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Qeyd')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma Tarixi')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_notes', to=settings.AUTH_USER_MODEL, verbose_name='Müəllif')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='onboarding.onboardingprocess', verbose_name='Prosess')),
            ],
            options={
                'verbose_name': 'Onboarding Qeydi',
                'verbose_name_plural': 'Onboarding Qeydləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
