# Generated by Django 4.2.23 on 2025-10-16 12:27

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0011_department_departments_department_tref4ab"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compensation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDepartmentBudget",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="Maliyyə İli")),
                (
                    "annual_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Departamentin illik maaş büdcəsi",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İllik Büdcə",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "utilized_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="İstifadə Olunan Məbləğ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="departments.department",
                        verbose_name="Departament",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Departament Büdcəsi",
                "verbose_name_plural": "historical Departament Büdcələri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="DepartmentBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fiscal_year", models.IntegerField(verbose_name="Maliyyə İli")),
                (
                    "annual_budget",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Departamentin illik maaş büdcəsi",
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İllik Büdcə",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "utilized_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=14,
                        verbose_name="İstifadə Olunan Məbləğ",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_budgets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="salary_budgets",
                        to="departments.department",
                        verbose_name="Departament",
                    ),
                ),
            ],
            options={
                "verbose_name": "Departament Büdcəsi",
                "verbose_name_plural": "Departament Büdcələri",
                "ordering": ["-fiscal_year"],
                "indexes": [
                    models.Index(
                        fields=["department", "fiscal_year"],
                        name="compensatio_departm_8dd155_idx",
                    )
                ],
                "unique_together": {("department", "fiscal_year")},
            },
        ),
    ]
