# Generated by Django 5.1.4 on 2025-10-16 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compensation", "0002_historicaldepartmentbudget_departmentbudget"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="salaryinformation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="salary_information",
                to=settings.AUTH_USER_MODEL,
                verbose_name="İstifadəçi",
            ),
        ),
    ]
