# Generated by Django 4.2.23 on 2025-10-21 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("compensation", "0003_alter_salaryinformation_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMarketBenchmark",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "position_title",
                    models.CharField(max_length=200, verbose_name="Vəzifə Adı"),
                ),
                (
                    "job_level",
                    models.CharField(
                        help_text="Məsələn: Entry, Mid, Senior",
                        max_length=50,
                        verbose_name="Vəzifə Səviyyəsi",
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="Sənaye"),
                ),
                (
                    "location",
                    models.CharField(
                        default="Bakı, Azərbaycan",
                        max_length=100,
                        verbose_name="Yerləşmə",
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Minimum Maaş"
                    ),
                ),
                (
                    "median_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Median Maaş"
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Maksimum Maaş"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "percentile_25",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="25-ci Persentil",
                    ),
                ),
                (
                    "percentile_75",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="75-ci Persentil",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("salary_survey", "Maaş Sorğusu"),
                            ("industry_report", "Sənaye Hesabatı"),
                            ("competitor_data", "Rəqib Məlumatları"),
                            ("job_board", "İş Elanları"),
                            ("recruitment_agency", "İşəqəbul Agentliyi"),
                            ("other", "Digər"),
                        ],
                        max_length=30,
                        verbose_name="Məlumat Mənbəyi",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Mənbə Adı"
                    ),
                ),
                (
                    "data_date",
                    models.DateField(
                        help_text="Bu məlumatın toplandığı tarix",
                        verbose_name="Məlumat Tarixi",
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Bu məlumata daxil olan işçi sayı",
                        null=True,
                        verbose_name="Nümunə Ölçüsü",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "Yüksək"),
                            ("medium", "Orta"),
                            ("low", "Aşağı"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Etibarlılıq Səviyyəsi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Bazar Müqayisəsi",
                "verbose_name_plural": "historical Bazar Müqayisələri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEquityGrant",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "equity_type",
                    models.CharField(
                        choices=[
                            ("stock_option", "Səhm Seçimi (Stock Option)"),
                            ("rsu", "Məhdudlaşdırılmış Səhm Vahidi (RSU)"),
                            ("sar", "Səhm Artım Hüququ (SAR)"),
                            ("phantom_stock", "Fantom Səhm"),
                            ("espp", "İşçi Səhm Alış Planı (ESPP)"),
                        ],
                        max_length=20,
                        verbose_name="Səhm Növü",
                    ),
                ),
                ("grant_date", models.DateField(verbose_name="Təqdim Tarixi")),
                ("number_of_shares", models.IntegerField(verbose_name="Səhm Sayı")),
                (
                    "strike_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stock options üçün - səhmi almaq üçün qiymət",
                        max_digits=12,
                        null=True,
                        verbose_name="İcra Qiyməti",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "vesting_schedule",
                    models.CharField(
                        choices=[
                            ("cliff", "Cliff (Birdəfəlik)"),
                            ("graded", "Qademeli"),
                            ("custom", "Xüsusi"),
                        ],
                        default="graded",
                        max_length=20,
                        verbose_name="Vesting Cədvəli",
                    ),
                ),
                (
                    "vesting_start_date",
                    models.DateField(verbose_name="Vesting Başlanğıc Tarixi"),
                ),
                (
                    "vesting_period_months",
                    models.IntegerField(
                        default=48,
                        help_text="Ümumi vesting müddəti aylarla",
                        verbose_name="Vesting Müddəti (ay)",
                    ),
                ),
                (
                    "cliff_months",
                    models.IntegerField(
                        default=12,
                        help_text="İlk vesting-dən əvvəl gözləmə müddəti",
                        verbose_name="Cliff Müddəti (ay)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("approved", "Təsdiqləndi"),
                            ("vesting", "Vesting Davam Edir"),
                            ("vested", "Tam Vested"),
                            ("exercised", "İcra Edildi"),
                            ("expired", "Müddəti Keçdi"),
                            ("cancelled", "Ləğv Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "vested_shares",
                    models.IntegerField(default=0, verbose_name="Vested Səhmlər"),
                ),
                (
                    "exercised_shares",
                    models.IntegerField(default=0, verbose_name="İcra Edilmiş Səhmlər"),
                ),
                (
                    "current_share_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Cari Səhm Dəyəri",
                    ),
                ),
                (
                    "last_valuation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Qiymətləndirmə Tarixi"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitmə Tarixi"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Səhm Təqdimi",
                "verbose_name_plural": "historical Səhm Təqdimləri",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MarketBenchmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_title",
                    models.CharField(max_length=200, verbose_name="Vəzifə Adı"),
                ),
                (
                    "job_level",
                    models.CharField(
                        help_text="Məsələn: Entry, Mid, Senior",
                        max_length=50,
                        verbose_name="Vəzifə Səviyyəsi",
                    ),
                ),
                (
                    "industry",
                    models.CharField(blank=True, max_length=100, verbose_name="Sənaye"),
                ),
                (
                    "location",
                    models.CharField(
                        default="Bakı, Azərbaycan",
                        max_length=100,
                        verbose_name="Yerləşmə",
                    ),
                ),
                (
                    "min_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Minimum Maaş"
                    ),
                ),
                (
                    "median_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Median Maaş"
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Maksimum Maaş"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "percentile_25",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="25-ci Persentil",
                    ),
                ),
                (
                    "percentile_75",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="75-ci Persentil",
                    ),
                ),
                (
                    "data_source",
                    models.CharField(
                        choices=[
                            ("salary_survey", "Maaş Sorğusu"),
                            ("industry_report", "Sənaye Hesabatı"),
                            ("competitor_data", "Rəqib Məlumatları"),
                            ("job_board", "İş Elanları"),
                            ("recruitment_agency", "İşəqəbul Agentliyi"),
                            ("other", "Digər"),
                        ],
                        max_length=30,
                        verbose_name="Məlumat Mənbəyi",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Mənbə Adı"
                    ),
                ),
                (
                    "data_date",
                    models.DateField(
                        help_text="Bu məlumatın toplandığı tarix",
                        verbose_name="Məlumat Tarixi",
                    ),
                ),
                (
                    "sample_size",
                    models.IntegerField(
                        blank=True,
                        help_text="Bu məlumata daxil olan işçi sayı",
                        null=True,
                        verbose_name="Nümunə Ölçüsü",
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("high", "Yüksək"),
                            ("medium", "Orta"),
                            ("low", "Aşağı"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="Etibarlılıq Səviyyəsi",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_benchmarks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bazar Müqayisəsi",
                "verbose_name_plural": "Bazar Müqayisələri",
                "ordering": ["-data_date", "position_title"],
                "indexes": [
                    models.Index(
                        fields=["position_title", "job_level"],
                        name="compensatio_positio_6be887_idx",
                    ),
                    models.Index(
                        fields=["industry", "location"],
                        name="compensatio_industr_e3d01c_idx",
                    ),
                    models.Index(
                        fields=["-data_date"], name="compensatio_data_da_99537f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EquityGrant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "equity_type",
                    models.CharField(
                        choices=[
                            ("stock_option", "Səhm Seçimi (Stock Option)"),
                            ("rsu", "Məhdudlaşdırılmış Səhm Vahidi (RSU)"),
                            ("sar", "Səhm Artım Hüququ (SAR)"),
                            ("phantom_stock", "Fantom Səhm"),
                            ("espp", "İşçi Səhm Alış Planı (ESPP)"),
                        ],
                        max_length=20,
                        verbose_name="Səhm Növü",
                    ),
                ),
                ("grant_date", models.DateField(verbose_name="Təqdim Tarixi")),
                ("number_of_shares", models.IntegerField(verbose_name="Səhm Sayı")),
                (
                    "strike_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Stock options üçün - səhmi almaq üçün qiymət",
                        max_digits=12,
                        null=True,
                        verbose_name="İcra Qiyməti",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                (
                    "vesting_schedule",
                    models.CharField(
                        choices=[
                            ("cliff", "Cliff (Birdəfəlik)"),
                            ("graded", "Qademeli"),
                            ("custom", "Xüsusi"),
                        ],
                        default="graded",
                        max_length=20,
                        verbose_name="Vesting Cədvəli",
                    ),
                ),
                (
                    "vesting_start_date",
                    models.DateField(verbose_name="Vesting Başlanğıc Tarixi"),
                ),
                (
                    "vesting_period_months",
                    models.IntegerField(
                        default=48,
                        help_text="Ümumi vesting müddəti aylarla",
                        verbose_name="Vesting Müddəti (ay)",
                    ),
                ),
                (
                    "cliff_months",
                    models.IntegerField(
                        default=12,
                        help_text="İlk vesting-dən əvvəl gözləmə müddəti",
                        verbose_name="Cliff Müddəti (ay)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("approved", "Təsdiqləndi"),
                            ("vesting", "Vesting Davam Edir"),
                            ("vested", "Tam Vested"),
                            ("exercised", "İcra Edildi"),
                            ("expired", "Müddəti Keçdi"),
                            ("cancelled", "Ləğv Edildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "vested_shares",
                    models.IntegerField(default=0, verbose_name="Vested Səhmlər"),
                ),
                (
                    "exercised_shares",
                    models.IntegerField(default=0, verbose_name="İcra Edilmiş Səhmlər"),
                ),
                (
                    "current_share_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Cari Səhm Dəyəri",
                    ),
                ),
                (
                    "last_valuation_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Son Qiymətləndirmə Tarixi"
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitmə Tarixi"
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Təsdiq Tarixi"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_equity_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Təsdiqləyən",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_equity_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equity_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Səhm Təqdimi",
                "verbose_name_plural": "Səhm Təqdimləri",
                "ordering": ["-grant_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="compensatio_user_id_672770_idx"
                    ),
                    models.Index(
                        fields=["grant_date"], name="compensatio_grant_d_abb7eb_idx"
                    ),
                    models.Index(
                        fields=["vesting_start_date"],
                        name="compensatio_vesting_14a9a9_idx",
                    ),
                ],
            },
        ),
    ]
