# Generated by Django 4.2.23 on 2025-10-22 19:59

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "compensation",
            "0004_historicalmarketbenchmark_historicalequitygrant_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "benefit_type",
                    models.CharField(
                        choices=[
                            ("health", "Səhiyyə Sığortası"),
                            ("dental", "Diş Sığortası"),
                            ("vision", "Göz Sığortası"),
                            ("life", "Həyat Sığortası"),
                            ("disability", "Əlillik Sığortası"),
                            ("pension", "Pensiya Töhfəsi"),
                            ("retirement", "Təqaüd Planı"),
                            ("education", "Təhsil Yardımı"),
                            ("gym", "İdman Mərkəzi"),
                            ("transport", "Nəqliyyat Yardımı"),
                            ("meal", "Yemək Kuponu"),
                            ("childcare", "Uşaq Baxımı Yardımı"),
                            ("mobile", "Mobil Telefon"),
                            ("laptop", "Laptop/Kompüter"),
                            ("relocation", "Köçürmə Yardımı"),
                            ("other", "Digər"),
                        ],
                        max_length=20,
                        verbose_name="Benefit Növü",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Sığorta şirkəti və ya xidmət təchizatçısı",
                        max_length=200,
                        verbose_name="Təchizatçı",
                    ),
                ),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("individual", "Fərdi"),
                            ("family", "Ailə"),
                            ("spouse", "Həyat Yoldaşı"),
                            ("children", "Uşaqlar"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="Əhatə Növü",
                    ),
                ),
                (
                    "annual_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="İşəgötürən tərəfindən ödənilən illik dəyər",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İllik Dəyər",
                    ),
                ),
                (
                    "employee_contribution",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="İşçi tərəfindən ödənilən məbləğ",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="İşçi Töhfəsi",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="AZN", max_length=3, verbose_name="Valyuta"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlanğıc Tarixi")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Bitmə Tarixi"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Aktiv"),
                            ("pending", "Gözləmədə"),
                            ("cancelled", "Ləğv Edildi"),
                            ("expired", "Müddəti Bitdi"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "policy_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Polis Nömrəsi"
                    ),
                ),
                (
                    "coverage_details",
                    models.TextField(blank=True, verbose_name="Əhatə Təfsilatı"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Qeydlər")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_benefits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İşçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İşçi Benefiti",
                "verbose_name_plural": "İşçi Benefitləri",
                "ordering": ["-start_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="compensatio_user_id_3d6a2e_idx"
                    ),
                    models.Index(
                        fields=["benefit_type"], name="compensatio_benefit_a7c4d1_idx"
                    ),
                    models.Index(
                        fields=["start_date"], name="compensatio_start_d_f3c721_idx"
                    ),
                ],
            },
        ),
    ]
