# Generated by Django 5.1.4 on 2026-07-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compensation', '0005_employeebenefit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='AZN, USD, EUR', max_length=3, unique=True, verbose_name='Valyuta Kodu')),
                ('name', models.CharField(max_length=50, verbose_name='Valyuta Adı')),
                ('symbol', models.CharField(max_length=5, verbose_name='Simvol')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1.0, max_digits=10, verbose_name='Məzənnə (AZN)')),
                ('is_base', models.BooleanField(default=False, verbose_name='Əsas Valyutadır')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'Valyuta',
                'verbose_name_plural': 'Valyutalar',
            },
        ),
        migrations.CreateModel(
            name='PayGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Ad')),
                ('level', models.IntegerField(help_text='İyerarxik səviyyə (1, 2, 3...)', verbose_name='Səviyyə')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'Maaş Dərəcəsi',
                'verbose_name_plural': 'Maaş Dərəcələri',
                'ordering': ['level', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dövr Adı')),
                ('start_date', models.DateField(verbose_name='Başlama Tarixi')),
                ('end_date', models.DateField(verbose_name='Bitmə Tarixi')),
                ('payment_date', models.DateField(verbose_name='Ödəniş Tarixi')),
                ('status', models.CharField(choices=[('DRAFT', 'Qaralama'), ('PROCESSING', 'İşlənir'), ('COMPLETED', 'Tamamlandı')], max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Ödəniş Dövrü',
                'verbose_name_plural': 'Ödəniş Dövrləri',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='SalaryBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Minimum Maaş')),
                ('mid_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Orta Maaş')),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Maksimum Maaş')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='compensation.currency', verbose_name='Valyuta')),
                ('pay_grade', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_band', to='compensation.paygrade', verbose_name='Maaş Dərəcəsi')),
            ],
            options={
                'verbose_name': 'Maaş Aralığı',
                'verbose_name_plural': 'Maaş Aralıqları',
            },
        ),
    ]
