# Generated by Django 4.2.23 on 2025-10-09 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Yaratma"),
                            ("update", "Yenilənmə"),
                            ("delete", "Silinmə"),
                            ("login", "Giriş"),
                            ("logout", "Çıxış"),
                            ("export", "İxrac"),
                            ("import", "İdxal"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="Model")),
                ("object_id", models.CharField(blank=True, max_length=50)),
                (
                    "changes",
                    models.JSONField(default=dict, verbose_name="Dəyişikliklər"),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Qeydi",
                "verbose_name_plural": "Audit Qeydləri",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_audit_user_id_a3c2bc_idx",
                    ),
                    models.Index(
                        fields=["action", "model_name"],
                        name="audit_audit_action_3e3f78_idx",
                    ),
                ],
            },
        ),
    ]
