# Generated by Django 5.1.4 on 2025-10-10 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Yaratma"),
                    ("update", "Yenilənmə"),
                    ("delete", "Silinmə"),
                    ("login", "Giriş"),
                    ("logout", "Çıxış"),
                    ("login_failure", "Uğursuz Giriş"),
                    ("export", "İxrac"),
                    ("import", "İdxal"),
                ],
                max_length=20,
            ),
        ),
    ]
