# Generated by Django 4.2.23 on 2025-10-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_alter_auditlog_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="actor_role",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="İstifadəçi Rolu"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="context",
            field=models.JSONField(blank=True, default=dict, verbose_name="Kontekst"),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="http_method",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="HTTP metodu"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Sorğu Yolu"
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="severity",
            field=models.CharField(
                choices=[
                    ("info", "Məlumat"),
                    ("warning", "Xəbərdarlıq"),
                    ("critical", "Kritik"),
                ],
                default="info",
                max_length=10,
                verbose_name="Şiddət",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="status_code",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Status Kodu"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "Yaratma"),
                    ("update", "Yenilənmə"),
                    ("delete", "Silinmə"),
                    ("login", "Giriş"),
                    ("logout", "Çıxış"),
                    ("login_failure", "Uğursuz Giriş"),
                    ("export", "İxrac"),
                    ("import", "İdxal"),
                    ("view", "Baxış"),
                    ("permission_denied", "İcazə Rədd Edildi"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["severity", "created_at"], name="audit_audit_severit_effc12_idx"
            ),
        ),
    ]
