# Generated by Django 5.1.4 on 2025-10-23 13:26

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_auditlog_actor_role_auditlog_context_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="audit_search_idx"
            ),
        ),
    ]
