# Generated by Django 5.1.4 on 2025-10-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0004_auditlog_search_vector_auditlog_audit_search_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="threat_level",
            field=models.CharField(
                choices=[
                    ("none", "Təhlükə yoxdur"),
                    ("low", "Aşağı"),
                    ("medium", "Orta"),
                    ("high", "Yüksək"),
                    ("critical", "Kritik"),
                ],
                default="none",
                max_length=10,
                verbose_name="Təhlükə Səviyyəsi",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="threat_score",
            field=models.IntegerField(default=0, verbose_name="Təhlükə Skoru"),
        ),
    ]
