# Generated by Django 5.1.4 on 2026-07-14 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_blockedip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Sorğu Qeydi',
                'verbose_name_plural': 'API Sorğu Qeydləri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İnsident Adı')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('severity', models.CharField(choices=[('info', 'Məlumat'), ('warning', 'Xəbərdarlıq'), ('critical', 'Kritik')], default='warning', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Açıq'), ('investigating', 'Araşdırılır'), ('resolved', 'Həll Edildi'), ('closed', 'Bağlandı')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('related_logs', models.ManyToManyField(blank=True, to='audit.auditlog', verbose_name='Əlaqəli Qeydlər')),
            ],
            options={
                'verbose_name': 'Təhlükəsizlik İnsidenti',
                'verbose_name_plural': 'Təhlükəsizlik İnsidentləri',
                'ordering': ['-created_at'],
            },
        ),
    ]
