# Generated by Django 5.1.4 on 2026-07-14 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0015_jobtitle_historicaljobtitle'),
        ('engagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Fəaliyyət Planı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('start_date', models.DateField(verbose_name='Başlama Tarixi')),
                ('end_date', models.DateField(verbose_name='Bitmə Tarixi')),
                ('status', models.CharField(choices=[('planned', 'Planlaşdırılıb'), ('in_progress', 'Davam Edir'), ('completed', 'Tamamlandı')], default='planned', max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
            options={
                'verbose_name': 'Engagement Fəaliyyət Planı',
                'verbose_name_plural': 'Engagement Fəaliyyət Planları',
            },
        ),
    ]
