# Generated by Django 4.2.23 on 2025-10-09 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Şablon Adı"
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Mövzu")),
                ("html_content", models.TextField(verbose_name="HTML Məzmun")),
                (
                    "text_content",
                    models.TextField(blank=True, verbose_name="Mətn Məzmunu"),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "E-poçt Şablonu",
                "verbose_name_plural": "E-poçt Şablonları",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "Məlumat"),
                            ("warning", "Xəbərdarlıq"),
                            ("success", "Uğur"),
                            ("error", "Xəta"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False, verbose_name="Oxundu")),
                (
                    "link",
                    models.CharField(blank=True, max_length=500, verbose_name="Keçid"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildiriş",
                "verbose_name_plural": "Bildirişlər",
                "ordering": ["-created_at"],
            },
        ),
    ]
