# Generated by Django 5.1.4 on 2025-10-17 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("notifications", "0002_emaillog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="Ad"),
                ),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("email", "E-poçt"),
                            ("sms", "SMS"),
                            ("push", "Push Bildirişi"),
                            ("in_app", "Tətbiqdaxili"),
                        ],
                        max_length=20,
                        verbose_name="Metod Növü",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivdir"),
                ),
                (
                    "configuration",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Konfiqurasiya"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Bildiriş Metodu",
                "verbose_name_plural": "Bildiriş Metodları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SMSProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Ad"),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("twilio", "Twilio"),
                            ("aws_sns", "AWS SNS"),
                            ("clickatell", "Clickatell"),
                            ("custom", "Fərdi"),
                        ],
                        max_length=20,
                        verbose_name="Təchizatçı",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivdir"),
                ),
                (
                    "configuration",
                    models.JSONField(default=dict, verbose_name="Konfiqurasiya"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SMS Təchizatçısı",
                "verbose_name_plural": "SMS Təchizatçıları",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("email", "E-poçt"),
                    ("sms", "SMS"),
                    ("push", "Push"),
                    ("in_app", "Tətbiqdaxili"),
                ],
                default="in_app",
                max_length=20,
                verbose_name="Kanal",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Aşağı"),
                    ("normal", "Normal"),
                    ("high", "Yüksək"),
                    ("urgent", "Təcili"),
                ],
                default="normal",
                max_length=20,
                verbose_name="Prioritet",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="scheduled_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Planlaşdırılmış Vaxt"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="sent_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Göndərilmə Vaxtı"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("info", "Məlumat"),
                    ("warning", "Xəbərdarlıq"),
                    ("success", "Uğur"),
                    ("error", "Xəta"),
                    ("assignment", "Tapşırıq"),
                    ("reminder", "Xatırlatma"),
                    ("security", "Təhlükəsizlik"),
                    ("announcement", "Elan"),
                ],
                default="info",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="BulkNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("message", models.TextField(verbose_name="Mesaj")),
                ("recipients_count", models.IntegerField(verbose_name="Alıcı Sayı")),
                (
                    "filter_criteria",
                    models.JSONField(
                        default=dict, verbose_name="Filtrləmə Kriteriyaları"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("in_progress", "Davam Edir"),
                            ("completed", "Tamamlandı"),
                            ("failed", "Uğursuz"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("channels", models.JSONField(default=list, verbose_name="Kanallar")),
                (
                    "sent_count",
                    models.IntegerField(default=0, verbose_name="Göndərilənlər Sayı"),
                ),
                (
                    "failed_count",
                    models.IntegerField(default=0, verbose_name="Uğursuzlar Sayı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "initiated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Başlatan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kütləvi Bildiriş",
                "verbose_name_plural": "Kütləvi Bildirişlər",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Şablon Adı"
                    ),
                ),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("campaign_start", "Qiymətləndirmə Kampaniyası Başlayır"),
                            ("campaign_end", "Qiymətləndirmə Kampaniyası Bitir"),
                            ("evaluation_assigned", "Qiymətləndirmə Tapşırılır"),
                            ("evaluation_completed", "Qiymətləndirmə Tamamlanır"),
                            ("report_ready", "Hesabat Hazırdır"),
                            ("deadline_reminder", "Bitmə Vaxtına Xatırlatma"),
                            ("new_training", "Yeni Təlim Təyin Edilir"),
                            ("training_complete", "Təlim Tamamlanır"),
                            ("salary_change", "Maaş Dəyişikliyi"),
                            ("performance_result", "Performans Nəticələri"),
                            ("system_maintenance", "Sistem Texniki Xidmət"),
                            ("password_change", "Şifrə Dəyişikliyi"),
                            ("account_lock", "Hesab Bloklanır"),
                            ("security_alert", "Təhlükəsizlik Xəbərdarlığı"),
                            ("general_announcement", "Ümumi Elan"),
                        ],
                        max_length=50,
                        verbose_name="Tətik",
                    ),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="Mövzu")),
                ("email_content", models.TextField(verbose_name="E-poçt Məzmunu")),
                (
                    "sms_content",
                    models.CharField(max_length=160, verbose_name="SMS Məzmunu"),
                ),
                (
                    "push_content",
                    models.CharField(max_length=200, verbose_name="Push Məzmunu"),
                ),
                ("inapp_content", models.TextField(verbose_name="Tətbiqdaxili Məzmun")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivdir"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "methods",
                    models.ManyToManyField(
                        blank=True,
                        to="notifications.notificationmethod",
                        verbose_name="Bildiriş Metodları",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildiriş Şablonu",
                "verbose_name_plural": "Bildiriş Şablonları",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PushNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlıq")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Əlavə Məlumat"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("sent", "Göndərildi"),
                            ("failed", "Uğursuz"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Xəta Mesajı"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Göndərilmə Vaxtı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Push Bildirişi",
                "verbose_name_plural": "Push Bildirişləri",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=20, verbose_name="Telefon Nömrəsi"),
                ),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("sent", "Göndərildi"),
                            ("failed", "Uğursuz"),
                            ("delivered", "Çatdırıldı"),
                            ("undelivered", "Çatdırılmadı"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Xarici ID"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="Xəta Mesajı"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Göndərilmə Vaxtı"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Çatdırılma Vaxtı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Alıcı",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.smsprovider",
                        verbose_name="Təchizatçı",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Loqu",
                "verbose_name_plural": "SMS Loqları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="E-poçt Bildirişləri"
                    ),
                ),
                (
                    "email_assignment",
                    models.BooleanField(
                        default=True, verbose_name="Tapşırıq Bildirişləri"
                    ),
                ),
                (
                    "email_reminder",
                    models.BooleanField(
                        default=True, verbose_name="Xatırlatma Bildirişləri"
                    ),
                ),
                (
                    "email_announcement",
                    models.BooleanField(default=True, verbose_name="Elan Bildirişləri"),
                ),
                (
                    "email_security",
                    models.BooleanField(
                        default=True, verbose_name="Təhlükəsizlik Bildirişləri"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(default=False, verbose_name="SMS Bildirişləri"),
                ),
                (
                    "sms_important_only",
                    models.BooleanField(
                        default=True, verbose_name="Yalnız Vacib Bildirişlər"
                    ),
                ),
                (
                    "sms_assignment",
                    models.BooleanField(
                        default=False, verbose_name="Tapşırıq Bildirişləri"
                    ),
                ),
                (
                    "sms_reminder",
                    models.BooleanField(
                        default=False, verbose_name="Xatırlatma Bildirişləri"
                    ),
                ),
                (
                    "sms_security",
                    models.BooleanField(
                        default=True, verbose_name="Təhlükəsizlik Bildirişləri"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(default=True, verbose_name="Push Bildirişləri"),
                ),
                (
                    "push_assignment",
                    models.BooleanField(
                        default=True, verbose_name="Tapşırıq Bildirişləri"
                    ),
                ),
                (
                    "push_reminder",
                    models.BooleanField(
                        default=True, verbose_name="Xatırlatma Bildirişləri"
                    ),
                ),
                (
                    "push_announcement",
                    models.BooleanField(default=True, verbose_name="Elan Bildirişləri"),
                ),
                (
                    "dnd_start_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Sakitlik Rejimi - Başlama"
                    ),
                ),
                (
                    "dnd_end_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Sakitlik Rejimi - Bitmə"
                    ),
                ),
                (
                    "weekend_notifications",
                    models.BooleanField(
                        default=True, verbose_name="Həftə Sonu Bildirişləri"
                    ),
                ),
                (
                    "weekday_start",
                    models.TimeField(default="08:00", verbose_name="İş Günü Başlama"),
                ),
                (
                    "weekday_end",
                    models.TimeField(default="18:00", verbose_name="İş Günü Bitmə"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "İstifadəçi Bildiriş Tənzimləmələri",
                "verbose_name_plural": "İstifadəçi Bildiriş Tənzimləmələri",
            },
        ),
    ]
