# Generated by Django 4.2.23 on 2025-10-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_smsnotification_pushnotification_priority_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsprovider",
            name="provider",
            field=models.CharField(
                choices=[
                    ("twilio", "Twilio"),
                    ("aws_sns", "AWS SNS"),
                    ("clickatell", "Clickatell"),
                    ("azercell", "Azercell"),
                    ("bakcell", "Bakcell"),
                    ("custom", "Fərdi"),
                ],
                max_length=20,
                verbose_name="Təchizatçı",
            ),
        ),
    ]
