# Generated by Django 4.2.23 on 2025-10-09 06:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Kampaniya Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("start_date", models.DateField(verbose_name="Başlama Tarixi")),
                ("end_date", models.DateField(verbose_name="Bitmə Tarixi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("active", "Aktiv"),
                            ("completed", "Tamamlanmış"),
                            ("archived", "Arxivlənmiş"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=True,
                        help_text="Qiymətləndirənin kimliyini gizlət",
                        verbose_name="Anonim Qiymətləndirmə",
                    ),
                ),
                (
                    "allow_self_evaluation",
                    models.BooleanField(
                        default=True, verbose_name="Özünüdəyərləndirməyə İcazə Ver"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "target_departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="evaluation_campaigns",
                        to="departments.department",
                        verbose_name="Hədəf Şöbələr",
                    ),
                ),
                (
                    "target_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="target_campaigns",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Hədəf İstifadəçilər",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qiymətləndirmə Kampaniyası",
                "verbose_name_plural": "Qiymətləndirmə Kampaniyaları",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="QuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Kateqoriya Adı"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Sual Kateqoriyası",
                "verbose_name_plural": "Sual Kateqoriyaları",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Sual Mətni")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("scale", "Bal Skalası (1-5)"),
                            ("boolean", "Bəli/Xeyr"),
                            ("text", "Açıq Cavab"),
                        ],
                        default="scale",
                        max_length=20,
                        verbose_name="Sual Növü",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Maksimum Bal",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Məcburi"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="evaluations.questioncategory",
                        verbose_name="Kateqoriya",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sual",
                "verbose_name_plural": "Suallar",
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalQuestion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("text", models.TextField(verbose_name="Sual Mətni")),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("scale", "Bal Skalası (1-5)"),
                            ("boolean", "Bəli/Xeyr"),
                            ("text", "Açıq Cavab"),
                        ],
                        default="scale",
                        max_length=20,
                        verbose_name="Sual Növü",
                    ),
                ),
                (
                    "max_score",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Maksimum Bal",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=True, verbose_name="Məcburi"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktiv")),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="evaluations.questioncategory",
                        verbose_name="Kateqoriya",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Sual",
                "verbose_name_plural": "historical Suallar",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEvaluationCampaign",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Kampaniya Adı"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Təsvir")),
                ("start_date", models.DateField(verbose_name="Başlama Tarixi")),
                ("end_date", models.DateField(verbose_name="Bitmə Tarixi")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Qaralama"),
                            ("active", "Aktiv"),
                            ("completed", "Tamamlanmış"),
                            ("archived", "Arxivlənmiş"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=True,
                        help_text="Qiymətləndirənin kimliyini gizlət",
                        verbose_name="Anonim Qiymətləndirmə",
                    ),
                ),
                (
                    "allow_self_evaluation",
                    models.BooleanField(
                        default=True, verbose_name="Özünüdəyərləndirməyə İcazə Ver"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yaradılma Tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, verbose_name="Yenilənmə Tarixi"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yaradan",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Qiymətləndirmə Kampaniyası",
                "verbose_name_plural": "historical Qiymətləndirmə Kampaniyaları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEvaluationAssignment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("self", "Özünüdəyərləndirmə"),
                            ("supervisor", "Rəhbər Tərəfindən"),
                            ("peer", "Həmkar Tərəfindən"),
                            ("subordinate", "Tabelik Tərəfindən"),
                        ],
                        max_length=20,
                        verbose_name="Əlaqə Növü",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("in_progress", "Davam edir"),
                            ("completed", "Tamamlanmış"),
                            ("expired", "Vaxtı Keçmiş"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlanma Vaxtı"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Vaxtı"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="evaluations.evaluationcampaign",
                        verbose_name="Kampaniya",
                    ),
                ),
                (
                    "evaluatee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirilən",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirən",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Qiymətləndirmə Tapşırığı",
                "verbose_name_plural": "historical Qiymətləndirmə Tapşırıqları",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="EvaluationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("self", "Özünüdəyərləndirmə"),
                            ("supervisor", "Rəhbər Tərəfindən"),
                            ("peer", "Həmkar Tərəfindən"),
                            ("subordinate", "Tabelik Tərəfindən"),
                        ],
                        max_length=20,
                        verbose_name="Əlaqə Növü",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gözləyir"),
                            ("in_progress", "Davam edir"),
                            ("completed", "Tamamlanmış"),
                            ("expired", "Vaxtı Keçmiş"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Başlanma Vaxtı"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tamamlanma Vaxtı"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="evaluations.evaluationcampaign",
                        verbose_name="Kampaniya",
                    ),
                ),
                (
                    "evaluatee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirilən",
                    ),
                ),
                (
                    "evaluator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="given_evaluations",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirən",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qiymətləndirmə Tapşırığı",
                "verbose_name_plural": "Qiymətləndirmə Tapşırıqları",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="Sıra")),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_questions",
                        to="evaluations.evaluationcampaign",
                        verbose_name="Kampaniya",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_uses",
                        to="evaluations.question",
                        verbose_name="Sual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kampaniya Sualı",
                "verbose_name_plural": "Kampaniya Sualları",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Bal",
                    ),
                ),
                (
                    "boolean_answer",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Bəli/Xeyr Cavabı"
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(blank=True, verbose_name="Mətn Cavabı"),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Şərh")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="evaluations.evaluationassignment",
                        verbose_name="Tapşırıq",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="evaluations.question",
                        verbose_name="Sual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cavab",
                "verbose_name_plural": "Cavablar",
                "ordering": ["assignment", "question__order"],
                "unique_together": {("assignment", "question")},
            },
        ),
        migrations.CreateModel(
            name="EvaluationResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Ümumi Bal",
                    ),
                ),
                (
                    "self_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Özünüdəyərləndirmə Balı",
                    ),
                ),
                (
                    "supervisor_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Rəhbər Balı",
                    ),
                ),
                (
                    "peer_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Həmkar Balı",
                    ),
                ),
                (
                    "subordinate_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Tabelik Balı",
                    ),
                ),
                (
                    "total_evaluators",
                    models.IntegerField(default=0, verbose_name="Qiymətləndirən Sayı"),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Tamamlanma Faizi",
                    ),
                ),
                (
                    "is_finalized",
                    models.BooleanField(default=False, verbose_name="Yekunlaşdırılmış"),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Yekunlaşdırma Vaxtı"
                    ),
                ),
                (
                    "calculated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Hesablama Vaxtı"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="evaluations.evaluationcampaign",
                        verbose_name="Kampaniya",
                    ),
                ),
                (
                    "evaluatee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluation_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Qiymətləndirilən",
                    ),
                ),
            ],
            options={
                "verbose_name": "Qiymətləndirmə Nəticəsi",
                "verbose_name_plural": "Qiymətləndirmə Nəticələri",
                "ordering": ["-calculated_at"],
                "unique_together": {("campaign", "evaluatee")},
            },
        ),
        migrations.AddIndex(
            model_name="evaluationcampaign",
            index=models.Index(
                fields=["status", "start_date"], name="evaluations_status_2985ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationcampaign",
            index=models.Index(
                fields=["end_date"], name="evaluations_end_dat_1d8a09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationassignment",
            index=models.Index(
                fields=["evaluator", "status"], name="evaluations_evaluat_b86b4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationassignment",
            index=models.Index(
                fields=["evaluatee", "campaign"], name="evaluations_evaluat_0b4546_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evaluationassignment",
            unique_together={("campaign", "evaluator", "evaluatee")},
        ),
        migrations.AlterUniqueTogether(
            name="campaignquestion",
            unique_together={("campaign", "question")},
        ),
    ]
