# Generated by Django 4.2.23 on 2025-10-10 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalquestion",
            name="max_score",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Qiymətləndirmə 1-5 şkalasında aparılır",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Maksimum Bal",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="max_score",
            field=models.PositiveIntegerField(
                default=5,
                help_text="Qiymətləndirmə 1-5 şkalasında aparılır",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Maksimum Bal",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="score",
            field=models.IntegerField(
                blank=True,
                help_text="1-5 arası qiymətləndirmə balı",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Bal",
            ),
        ),
    ]
