# Generated by Django 5.1.4 on 2025-10-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("evaluations", "0002_update_score_validators_to_5"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="sentiment_category",
            field=models.CharField(
                choices=[
                    ("positive", "Pozitiv"),
                    ("negative", "Neqativ"),
                    ("neutral", "Neytral"),
                ],
                default="neutral",
                max_length=20,
                verbose_name="Sentiment Kateqoriyası",
            ),
        ),
        migrations.AddField(
            model_name="response",
            name="sentiment_score",
            field=models.FloatField(
                default=0.0,
                help_text="VADER sentiment compound skoru (-1.0 - +1.0)",
                verbose_name="Sentiment Skoru",
            ),
        ),
    ]
