# Generated by Django 5.1.4 on 2025-10-11 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("departments", "0004_historicalposition_level"),
        ("evaluations", "0003_response_sentiment_category_response_sentiment_score"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="evaluationcampaign",
            index=models.Index(fields=["status"], name="evaluations_status_540c61_idx"),
        ),
        migrations.AddIndex(
            model_name="evaluationcampaign",
            index=models.Index(
                fields=["created_by"], name="evaluations_created_4c6f18_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationresult",
            index=models.Index(
                fields=["campaign", "evaluatee"], name="evaluations_campaig_8f9381_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationresult",
            index=models.Index(
                fields=["evaluatee"], name="evaluations_evaluat_9c92c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationresult",
            index=models.Index(
                fields=["overall_score"], name="evaluations_overall_3cb2fe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evaluationresult",
            index=models.Index(
                fields=["is_finalized"], name="evaluations_is_fina_aa3421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["category", "is_active"], name="evaluations_categor_12d1ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["question_type"], name="evaluations_questio_fd93e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["is_active"], name="evaluations_is_acti_c4763a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["assignment", "question"], name="evaluations_assignm_343623_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["assignment"], name="evaluations_assignm_f87987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["question"], name="evaluations_questio_35127c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="response",
            index=models.Index(
                fields=["sentiment_category"], name="evaluations_sentime_2bf585_idx"
            ),
        ),
    ]
