# Generated by Django 5.1.4 on 2025-10-15 16:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "evaluations",
            "0004_evaluationcampaign_evaluations_status_540c61_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationcampaign",
            name="weight_peer",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Yekun balda həmkar qiymətləndirməsinin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Həmkar Çəkisi (%)",
            ),
        ),
        migrations.AddField(
            model_name="evaluationcampaign",
            name="weight_self",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Yekun balda özünüdəyərləndirmənin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Özünüdəyərləndirmə Çəkisi (%)",
            ),
        ),
        migrations.AddField(
            model_name="evaluationcampaign",
            name="weight_subordinate",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Yekun balda tabelik qiymətləndirməsinin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Tabelik Çəkisi (%)",
            ),
        ),
        migrations.AddField(
            model_name="evaluationcampaign",
            name="weight_supervisor",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Yekun balda rəhbər qiymətləndir\u200bməsinin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Rəhbər Çəkisi (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalevaluationcampaign",
            name="weight_peer",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Yekun balda həmkar qiymətləndirməsinin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Həmkar Çəkisi (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalevaluationcampaign",
            name="weight_self",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="Yekun balda özünüdəyərləndirmənin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Özünüdəyərləndirmə Çəkisi (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalevaluationcampaign",
            name="weight_subordinate",
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text="Yekun balda tabelik qiymətləndirməsinin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Tabelik Çəkisi (%)",
            ),
        ),
        migrations.AddField(
            model_name="historicalevaluationcampaign",
            name="weight_supervisor",
            field=models.DecimalField(
                decimal_places=2,
                default=50.0,
                help_text="Yekun balda rəhbər qiymətləndir\u200bməsinin çəkisi",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Rəhbər Çəkisi (%)",
            ),
        ),
    ]
