# Generated by Django 5.1.4 on 2026-07-06 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0005_evaluationcampaign_weight_peer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Köhnə Bal')),
                ('new_score', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Yeni Bal')),
                ('justification', models.TextField(blank=True, verbose_name='Əsaslandırma')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarix')),
                ('calibrated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kalibrləyən Şəxs')),
                ('evaluation_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='evaluations.evaluationresult', verbose_name='Qiymətləndirmə Nəticəsi')),
            ],
            options={
                'verbose_name': 'Kalibrləmə Logu',
                'verbose_name_plural': 'Kalibrləmə Logları',
                'ordering': ['-created_at'],
            },
        ),
    ]
