# Generated by Django 5.1.4 on 2026-07-14 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluations', '0006_calibrationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_days', models.IntegerField(default=3, verbose_name='Xatırlatma Günləri')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='Anonimliyə icazə ver')),
                ('default_self_weight', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Defolt Özünüdəyərləndirmə Çəkisi')),
                ('default_supervisor_weight', models.DecimalField(decimal_places=2, default=50.0, max_digits=5, verbose_name='Defolt Rəhbər Çəkisi')),
                ('default_peer_weight', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Defolt Həmkar Çəkisi')),
                ('default_subordinate_weight', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Defolt Tabelik Çəkisi')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qiymətləndirmə Parametri',
                'verbose_name_plural': 'Qiymətləndirmə Parametrləri',
            },
        ),
        migrations.CreateModel(
            name='ReviewCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Dövr Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('start_date', models.DateField(verbose_name='Başlama Tarixi')),
                ('end_date', models.DateField(verbose_name='Bitmə Tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rəy Dövrü',
                'verbose_name_plural': 'Rəy Dövrləri',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Şablon Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
            ],
            options={
                'verbose_name': 'Qiymətləndirmə Şablonu',
                'verbose_name_plural': 'Qiymətləndirmə Şablonları',
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.question', verbose_name='Sual')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='evaluations.evaluationtemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Şablon Sualı',
                'verbose_name_plural': 'Şablon Sualları',
                'ordering': ['order'],
            },
        ),
    ]
