# Generated by Django 5.1.4 on 2026-07-07 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competencies', '0002_competency_competencie_name_eac81b_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Görüş Tarixi')),
                ('status', models.CharField(choices=[('scheduled', 'Planlaşdırılıb'), ('in_progress', 'Davam Edir'), ('completed', 'Tamamlanıb'), ('cancelled', 'Ləğv Edilib')], default='scheduled', max_length=20, verbose_name='Status')),
                ('overall_notes', models.TextField(blank=True, verbose_name='Ümumi Qeydlər')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL, verbose_name='İşçi')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Rəhbər')),
            ],
            options={
                'verbose_name': '1-on-1 Görüş',
                'verbose_name_plural': '1-on-1 Görüşlər',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200, verbose_name='Mövzu')),
                ('content', models.TextField(verbose_name='Məzmun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='performance_reviews.reviewsession')),
            ],
            options={
                'verbose_name': 'Görüş Qeydi',
                'verbose_name_plural': 'Görüş Qeydləri',
            },
        ),
        migrations.CreateModel(
            name='ReviewActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Təsvir')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Bitmə Tarixi')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Tamamlanıb')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='performance_reviews.reviewsession')),
            ],
            options={
                'verbose_name': 'Görüləcək İş',
                'verbose_name_plural': 'Görüləcək İşlər',
            },
        ),
        migrations.CreateModel(
            name='CompetencyEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Rəy/Şərh')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_evaluations', to='competencies.competency')),
                ('manager_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='competencies.proficiencylevel', verbose_name='Rəhbər Qiymətləndirməsi')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_evaluations', to='performance_reviews.reviewsession')),
            ],
            options={
                'verbose_name': 'Kompetensiya Qiymətləndirməsi',
                'verbose_name_plural': 'Kompetensiya Qiymətləndirmələri',
                'unique_together': {('session', 'competency')},
            },
        ),
    ]
