# Generated by Django 5.1.4 on 2026-07-14 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wellness', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Müavinət/Sığorta Adı')),
                ('provider', models.CharField(max_length=100, verbose_name='Təminatçı')),
                ('coverage_details', models.TextField(blank=True, verbose_name='Əhatə Dairəsi')),
                ('start_date', models.DateField(verbose_name='Başlanğıc Tarixi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitmə Tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wellness_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Müavinət/Sığorta',
                'verbose_name_plural': 'Müavinətlər',
            },
        ),
        migrations.CreateModel(
            name='HealthGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Hədəf Adı')),
                ('description', models.TextField(blank=True, verbose_name='Təsvir')),
                ('target_date', models.DateField(verbose_name='Hədəf Tarixi')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('completed', 'Tamamlandı'), ('abandoned', 'Dayandırıldı')], default='active', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sağlamlıq Hədəfi',
                'verbose_name_plural': 'Sağlamlıq Hədəfləri',
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=100, verbose_name='Peyvənd Adı')),
                ('dose_number', models.IntegerField(default=1, verbose_name='Doza Nömrəsi')),
                ('administered_date', models.DateField(verbose_name='Vurulma Tarixi')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Növbəti Doza Tarixi')),
                ('notes', models.TextField(blank=True, verbose_name='Qeydlər')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peyvənd Qeydi',
                'verbose_name_plural': 'Peyvənd Qeydləri',
            },
        ),
    ]
